---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: activeiq, active iq digital advisor, features, upgrade, support offering 
summary: ダッシュボード、監視リスト、機能、ウィジェットに関する情報を提供します。 
---
= Active IQ の機能を理解する
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Active IQ デジタルアドバイザを使用して、ストレージシステムの全体的なステータス、システムの健全性に関する概要情報、インベントリ、計画、アップグレード、および監視リストレベルの価値ある分析情報を確認できます。

Active IQ デジタルアドバイザに初めてアクセスするときは、ウォッチリストを作成するか、顧客名、サイト名、グループ名、 StorageGRID 、ホスト名、 クラスタ、シリアル番号、またはシステム ID 。

また、カードに適用される色についても注意する必要があります。色は、リスクの重大度とタイプを示します。

Active IQ デジタルアドバイザの機能の一部を以下に示します。

* 複数の監視リストを表示し、実用的で有用な情報を一目で確認できます
* ストレージシステムにもたらされるすべてのリスクに関する分析情報を入手できます リスクを軽減するためのアクションも含まれます
* Active IQ Unified Manager を使用してリスクを軽減
* ストレージシステムをアップグレードします
* ONTAP 9.1 以降を実行しているストレージシステムのストレージ効率化率、使用済み論理スペース、使用済み物理スペース、および削減された合計データを表示します
* を表示して、ストレージデバイスのパフォーマンスを分析します パフォーマンスデータのグラフ形式
* 期限切れのハードウェアおよびソフトウェアに関する情報を取得します または、今後 6 か月以内に期限切れに近いものとします
* Ansible を使用して ONTAP ファームウェアを更新します
* 容量の 90% を超えたシステムまたはを超えたシステムに関する詳細を確認できます 容量の使用率が 90% に近づいています
* クラスタとノードの構成の概要、ローカル階層とボリュームの情報、ネットワークインターフェイスとポートの情報、ディスクとシェルフに関する詳細な情報を示すスタック図、およびケーブルで確認可能な図など、物理 / 論理構成の詳細な情報を表示します
* トラブルシューティング、アップグレード評価、ソリューションの検証、移行に役立つクロススタック情報と分析情報を提供
* ホストの互換性を確認し、ホストのオペレーティングシステム、ドライバ、およびファームウェアのアップグレードに関する推奨事項を提供します
* で見つけたいと思うものに丁度到着しなさい よりスマートで高速な方法



NOTE: サポートサービスをシステムダッシュボードの * 構成 * ウィジェットからアップグレードすると、インストールベースに関する情報を取得し、お客様に合わせたサポートを受けることができます。
