---
sidebar: sidebar 
permalink: concept_get_started_with_health_check_dashboard.html 
keywords: activeiq, health check, health, hca, health check dashboard, autosupport, autosupport adoption, recommended configuration, best practices, support, support and entitlements, support contract, contracts, active contracts, expired contracts, nearing-expiration, key recommendations, recommendations, digital advisor, features, recommended software 
summary: ダッシュボード、ヘルススコア、機能、ウィジェットに関する情報を提供します。 
---
= Digital Advisorヘルスチェックダッシュボードを使い始める
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このダッシュボードでは、次のウィジェットを使用してインストールベースの概要を一目で把握できます。

* *AutoSupport 導入状況*：AutoSupport が有効になっているシステムの数と割合を表示します。「Declined」とマークされたシステム、*HTTPS* と *AutoSupport on Demand* が有効になっているシステム、および過去 7 日間に AutoSupport データの送信を停止したシステムの *Loss of Signal* も表示できます。インストールベースのシステムに関するヘルスチェックスコアと情報を表示するには、*AutoSupport Adoption* ウィジェットを選択してください。
* * 推奨構成 * ： * 推奨構成 * ウィジェットに従って、準拠および非準拠のシステムを表示します。これは、システムがインストールベース全体にわたって適切に構成されていることを確認するためのアクションを実行するのに役立ちます。ダッシュボードに表示されたスコアを確認し、優先度順に提示された主要な推奨事項に基づいて操作を実行できます。
* * 推奨ソフトウェア *: すべてのソフトウェアおよびファームウェアのアップグレードおよび通貨に関する推奨事項の統合リストを表示します。AutoSupport が有効になっており、ソフトウェアまたはファームウェアのバージョンが最小か最新であるシステムを表示できます。
* *サポートと権利*：期限切れのサポート契約と、6～12か月以内に期限切れとなるサポート契約を表示します。サポート終了となったプラットフォーム、ディスク、シェルフ、ライセンスの遵守状況、有効期限切れ間近、およびプラットフォームとハードウェアのサポート終了が該当しないことを示します。ダッシュボードに表示される健康状態チェックのスコアを確認し、優先順位順に示されている主要な推奨事項に基づいて対策を講じることができます。サポート契約に関する詳細情報を表示するには、「サポートと権利」ウィジェットを選択してください。このウィジェットを使用してサポート契約を更新することもできます。
* * ベストプラクティス * ：パフォーマンスと効率性、可用性と保護、容量、構成、セキュリティの脆弱性など、ストレージシステムのベストプラクティス属性を評価することにより、健全性チェックのスコアを表示します。ネットアップのベストプラクティスはシステムヘルスの維持に役立ちます。これにより、インストールベースのパフォーマンスが最適化されます。
* * テクニカルケース * ：選択可能な期間にわたって、ケースタイプおよびオープンまたはクローズステータス別に、テクニカルケースの履歴を詳細に表示します。  ケースグループにドリルダウンしたり、でケースの詳細を確認したりできます link:https://mysupport.netapp.com//["NetApp Support Site"^] またはその他のケースポータル。

