---
sidebar: sidebar 
permalink: concept_autosupport.html 
keywords: AutoSupport 
summary: AutoSupport の概要を示します。 
---
= AutoSupport とは
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
AutoSupport は、システムの健常性をプロアクティブに監視し、設定、ステータス、パフォーマンス、およびシステムイベントのデータをネットアップに自動的に送信する計測メカニズムです。

このデータは、ネットアップテクニカルサポートが問題の診断と解決を高速化するために使用し、Digital Advisorが潜在的な問題をプロアクティブに検出して回避するために使用します。また、社内のサポート部門やサポートパートナーにも送信できます。


NOTE: Digital Advisorは、AutoSupport データが60日以内のシステムについてのみAutoSupport 関連データを表示します。

ONTAP システムでは、ストレージシステムの初回設定時に、 AutoSupport がデフォルトで有効になります。お勧めします link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/GUID-91C43742-E563-442E-8161-17D5C5DA8C19.html["AutoSupport をセットアップする"^] ONTAP システムで、テクニカルサポートおよび社内のサポート部門に AutoSupport 情報を送信する方法を制御します。

AutoSupport を有効にしたくない場合は、 AutoSupport のアップロード機能を使用して AutoSupport データを手動でアップロードし、ストレージエコシステムに関する推奨事項や分析情報を入手できます。


NOTE: AutoSupport データにユーザデータが含まれることはありません。

AutoSupport の詳細については、該当するドキュメントを参照してください。

* link:https://docs.netapp.com/us-en/ontap/system-admin/manage-autosupport-concept.html["ONTAP （ FAS および AFF ）"^]
* link:https://docs.netapp.com/us-en/storagegrid-117/admin/what-is-autosupport.html["StorageGRID"^]
* link:https://docs.netapp.com/us-en/e-series-santricity/sm-support/autosupport-feature-overview.html["SANtricity （ E シリーズおよび EF シリーズ）"^]
* link:https://docs.netapp.com/us-en/solidfire-active-iq/concept-active-iq-learn-about-active-iq.html["要素（ NetApp HCI および SolidFire ）"^]
* link:https://www.netapp.com/pdf.html?item=/media/10438-tr-4444pdf.pdf["テクニカルレポート - ONTAP AutoSupport and AutoSupport On Demand をご覧ください"^]
* link:https://www.netapp.com/pdf.html?item=/media/10439-tr4688pdf.pdf["テクニカルレポート - ネットアップ計測データのセキュリティとプライバシー"^]

