---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: digital advisor, features, upgrade, support offering 
summary: ダッシュボード、監視リスト、機能、ウィジェットに関する情報を提供します。 
---
= Digital Advisorの機能を理解する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisorを使用して、ストレージシステムの全体的なステータス、システムの健全性に関する概要、インベントリ、計画、アップグレード、重要な分析情報を監視リストレベルで確認できます。

初めてDigital Advisorにアクセスするときは、ウォッチリストを作成するか、顧客名、サイト名、グループ名、StorageGRID 、ホスト名、 クラスタ、シリアル番号、またはシステムID。

また、カードに適用される色についても注意する必要があります。色は、リスクの重大度とタイプを示します。

Digital Advisorの機能の一部を以下に示します。

* 複数の監視リストを表示し、実用的で有用な情報を一目で確認できます。
* ストレージシステムのすべてのリスクとリスクを軽減するためのアクションに関する分析情報を取得できます。
* Active IQ Unified Managerを使用してリスクを軽減します。
* ストレージシステムをアップグレードします。
* 持続可能性スコア、電力、直接炭素、熱の予測使用量を表示します。持続可能性スコアに基づいて、ストレージ システムの全体的な効率を評価し、スコアを向上させるために NetApp の推奨アクションに従います。link:learn-about-sustainability.html["詳細はこちら。"^] 。
* ONTAP 9.1以降を実行するストレージシステムのデータ削減率、使用済み論理スペース、使用済み物理スペース、削減された総データ量を表示します。
* パフォーマンスデータをグラフ形式で表示して、ストレージデバイスのパフォーマンスを分析します。
* 6カ月以内に有効期限が切れた、または有効期限が近づいているハードウェアおよびソフトウェアに関する情報を入手できます。
* Ansibleを使用してONTAPファームウェアを更新します。
* 容量が90%を超えているシステムや容量の90%に近づいているシステムに関する詳細を確認できます。
* 物理/論理構成の詳細情報を表示します。これには、クラスタとノードの構成の概要、ローカル階層とボリュームの情報、ネットワークインターフェイスとポートの情報、ディスクとシェルフに関する詳細なスタック図、ケーブルの可視化などが含まれます。
* トラブルシューティング、アップグレードの評価、解決策の検証、移行に役立つクロススタックの情報と分析情報を提供
* ホストの互換性を確認し、ホストオペレーティングシステム、ドライバ、およびのアップグレードに関する推奨事項を提供します。
* よりスマートで迅速な方法で見つけたいものに正確に到達します。



NOTE: サポートサービスをシステムダッシュボードの * 構成 * ウィジェットからアップグレードすると、インストールベースに関する情報を取得し、お客様に合わせたサポートを受けることができます。
