---
sidebar: sidebar 
permalink: concept_understand_activeiq_features.html 
keywords: activeiq, active iq digital advisor, features, 
summary: ダッシュボード、監視リスト、機能、ウィジェットに関する情報を提供します。 
---
= Active IQ の機能を理解する
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Active IQ デジタルアドバイザダッシュボードには、ストレージシステムの全体的なステータスに関する情報が表示されます。システムの健全性に関する概要情報、インベントリ、計画、アップグレード、監視リストレベルの価値ある分析情報が表示されます。ダッシュボードの健全性スコアも確認できます。健全性スコアを取得すると、高いリスクの数と期限切れの契約数に基づいて、インストールベースの総合スコアをお客様に提供できます。

Active IQ デジタルアドバイザに初めてアクセスしたとき、デフォルトでは、ダッシュボードに入力された情報はお客様の ID に基づいています。これで、最大 50 個のダッシュボードを作成し、これらのダッシュボードに監視リストを追加できます。

また、カードに適用される色についても注意する必要があります。色は、リスクの重大度とタイプを示します。

Active IQ デジタルアドバイザダッシュボードでは、次の操作を実行できます。

* 複数のダッシュボードを表示し、実用的でわかりやすい情報を一目で確認できます
* ストレージシステムにもたらされるすべてのリスクに関する分析情報を入手できます リスクを軽減するためのアクションも含まれます
* Active IQ Unified Manager を使用してリスクを軽減
* ストレージシステムをアップグレードします
* ONTAP 9.1 以降を実行しているストレージシステムのストレージ効率化率、使用済み論理スペース、使用済み物理スペース、および削減された合計データを表示します
* を表示して、ストレージデバイスのパフォーマンスを分析します パフォーマンスデータのグラフ形式
* 期限切れのハードウェアおよびソフトウェアに関する情報を取得します または、今後 6 か月以内に期限切れに近いものとします
* Ansible を使用して ONTAP ファームウェアを更新します
* 容量の 90% を超えたシステムまたはを超えたシステムに関する詳細を確認できます 容量の使用率が 90% に近づいています
* クラスタとノードの構成の概要、ローカル階層とボリュームの情報、ネットワークインターフェイスとポートの情報、ディスクとシェルフに関する詳細な情報を示すスタック図、およびケーブルで確認可能な図など、物理 / 論理構成の詳細な情報を表示します
* トラブルシューティング、アップグレード評価、ソリューションの検証、移行に役立つクロススタック情報と分析情報を提供
* ホストの互換性を確認し、ホストのオペレーティングシステム、ドライバ、およびファームウェアのアップグレードに関する推奨事項を提供します
* で見つけたいと思うものに丁度到着しなさい よりスマートで高速な方法

