---
sidebar: sidebar 
permalink: concept_overview_API_service.html 
keywords: API services, access token, refresh token, API Catalog 
summary: API サービス機能の概要を示します。 
---
= API サービスを理解する
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Active IQ API サービスでは、自動化を使用してワークフローを効率化します。API サービスは、 20 以上の異なるサービス領域にグループ化された 100 を超える API エンドポイントを記述した * API カタログ * を提供します。これらの API はネットアップのお客様が利用でき、システム情報、ストレージ効率、パフォーマンス、健常性、アップグレードなど、さまざまな目的に利用できます。

API は、プログラムによって Active IQ Digital Advisor にアクセスし、コンピューティング環境にデータを戻すことができるシンプルなコードを記述できるインターフェイスです。Active IQ デジタルアドバイザに毎日連絡し、関心のある分野の最新データを返すような方法でコードを記述することができます。その後、このデータを使用してチケット処理システムにデータを入力したり、独自のダッシュボード、 Web ページ、レポートを作成したりできます。Active IQ API カタログには、コードサンプルとファシリティの両方が含まれており、ブラウザで API を試してください。

API による自動化は、毎日または毎週のタスクに効率性と正確性を追加する優れた方法です。リソースが解放され、より複雑なアクティビティの実行や新しいワークフローの自動化が可能になります。たとえば、修正が必要なシステムヘルスリスクがある場合、少なくとも Active IQ デジタルアドバイザからのそれらの項目の引き出しとチケットシステムへのプッシュを自動化できます。



== API カタログ

ページ上部の切り替えボタンを使用すると、 2 つのモードを切り替えてカタログを表示できます。コードビューでは、必要な入力パラメータ、戻りデータの内容と形式、およびコードサンプルに焦点を当てて、ユーザがコードを適切に設定し始めるようにします。Experiment ビューでは、メインの API Services ページから取得した生成されたトークンを使用して、ブラウザで API を「試してみる」ことができます。

どちらのビューでも、左側のナビゲーションペインを使用して、使用可能な項目を参照できます。項目はサービスごとにアルファベット順に分類されています。特定のサービス内で、見出しを展開すると個々の API エンドポイントが表示されます。サービスヘッダーまたは API エンドポイントをクリックすると、中央のペインにあるカタログの該当するセクションに移動します。



== API を使用する

認証され、トークンを生成できるようになったら、トークンを利用して、プログラムによるクエリを作成したり、データを取得したりできます。API カタログ内から API をテストして、クエリの仕組みと返されるデータのタイプを一元的に確認することもできます。これは、システムでコードフレームワークを構築する前に、 API がどのように機能するかを理解するのに役立ちます。

video::GQskCeCrtQA[youtube, width=848,height=480]