---
sidebar: sidebar 
permalink: digital-advisor-integration-with-bluexp.html 
keywords: digital advisor, integration, bluexp 
summary: 'Digital Advisor (以前のActive IQ Digital Advisor )は"BlueXPと完全に統合されましたクラスタを管理し、BlueXPユーザーインターフェイス(UI)からDigital Advisorのすべての機能にアクセスできるようになりました。' 
---
= Digital AdvisorとBlueXPの統合
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Digital Advisor (以前のActive IQ Digital Advisor )は'BlueXPと完全に統合されましたクラスタを管理し、BlueXPユーザーインターフェイス(UI)からDigital Advisorのすべての機能にアクセスできるようになりました。

BlueXPを使用することで、ITエキスパートとクラウドアーキテクトはハイブリッドマルチクラウドインフラを一元管理できます。必要なのは、BlueXPのDigital AdvisorにアクセスするためのNetApp Support Site （NSS）アカウントだけです。



== 統合の概要

2022年11月より、Digital Advisorを使用することを推奨します。BlueXPからは、以前と同じDigital Advisorインターフェイスにアクセスできます。BlueXPを使用すると、クラウドストレージ（Cloud Volumes ONTAP など）の作成と管理、ネットアップのデータサービス（クラウドバックアップなど）の利用、オンプレミスとエッジのストレージデバイスの制御が可能になります。



== BlueXPのDigital Advisorにアクセスします

クラスタを管理するには、BlueXPからDigital Advisorにアクセスします。

.手順
. Web ブラウザを開き、に進みます https://cloudmanager.netapp.com/app-redirect/active-iq["BlueXP"^]
. 「* NetApp Support Site 資格情報でログイン*」を選択し、資格情報を入力します。
+
以前に電子メールとパスワードを使用してBlueXPログインを作成していた場合は、代わりにそのログインオプションを使用する必要があります。

. プロンプトが表示されたら、NetApp Support Site クレデンシャルを使用してログインします。
+
このログインは、手順2で完了したログインとは異なります。手順2では、BlueXPプラットフォームにログインしました。次にDigital Advisorにログインします。



* 結果 *

既存の監視リストと設定がすべて表示されるので、通常の場合と同様にDigital Advisorを使用できます。



== BlueXPの詳細をご覧ください

https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["詳細については、BlueXPのマニュアルを参照してください"^]
