---
sidebar: sidebar 
permalink: digital-advisor-integration-with-console.html 
keywords: digital advisor, integration, netapp console 
summary: 'Digital AdvisorはNetApp Console と完全に統合されました。  NetAppコンソール ユーザー インターフェイス (UI) からクラスターを管理し、 Digital Advisorのすべての機能にアクセスできるようになりました。' 
---
= NetAppコンソールでDigital Advisorにアクセスする
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital AdvisorはNetApp Console と完全に統合されました。コンソール ユーザー インターフェース (UI) からクラスターを管理し、 Digital Advisorのすべての機能にアクセスできるようになりました。

コンソールを使用すると、IT 専門家とクラウド アーキテクトはハイブリッド マルチクラウド インフラストラクチャを集中管理できます。コンソールのDigital Advisorにアクセスするために必要なのは、 NetAppサポート サイト (NSS) アカウントだけです。



[[netapp-console]]
== NetAppコンソール

Digital Advisor はNetAppコンソールからアクセスできます。

NetAppコンソールは、オンプレミスとクラウド環境全体にわたるエンタープライズ グレードのNetAppストレージとデータ サービスの集中管理を提供します。 NetAppデータ サービスにアクセスして使用するには、コンソールが必要です。管理インターフェースとして、1 つのインターフェースから多数のストレージ リソースを管理できます。コンソール管理者は、企業内のすべてのシステムのストレージとサービスへのアクセスを制御できます。

NetApp Console の使用を開始するためにライセンスやサブスクリプションは必要ありません。ストレージ システムや NetApp データ サービスへの接続を確保するためにクラウドに Console エージェントをデプロイする必要がある場合にのみ料金が発生します。ただし、Console からアクセスできる一部の NetApp データ サービスは、ライセンスまたはサブスクリプションが必要です。

 https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetAppコンソール"]の詳細については、こちらをご覧ください。

コンソールからDigital Advisorにアクセスしてクラスターを管理できます。

.手順
. ウェブブラウザを開いて、link:https://console.netapp.com/["コンソール"^] 。
. 「* NetApp Support Site 資格情報でログイン*」を選択し、資格情報を入力します。
+
以前にメールアドレスとパスワードを使用してコンソールログインを作成している場合は、引き続きそのログイン方法を使用する必要があります。

. プロンプトが表示されたら、NetApp Support Site クレデンシャルを使用してログインします。
+
このログインは、手順2で完了したログインとは異なります。手順2では、コンソールにログインしました。現在、Digital Advisor にログインしています。



* 結果 *

既存の監視リストと設定がすべて表示されるので、通常の場合と同様にDigital Advisorを使用できます。
