---
sidebar: sidebar 
permalink: learn-about-sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, benefits, ontap, netapp console 
summary: エネルギー消費量を削減し、環境目標に向けた取り組みを可能にする持続可能性に関する情報を提供します。 
---
= Digital Advisorで持続可能性について学ぶ
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
持続可能性により、エネルギー消費を削減し、環境目標に向けて取り組むことが可能になります。これにより、ストレージ システムを環境に配慮した慣行に適合させ、持続可能性の目標を達成できるようになります。

サステナビリティダッシュボードでは、サステナビリティスコア、電力使用量、直接炭素排出量、熱使用量の予測値を確認できます。特定のサイトごとに、炭素排出削減率を調整できます。クラスターレベルでのサステナビリティスコアも確認できます。サステナビリティスコアに基づいて、サステナビリティの状況を評価し、スコアを向上させるためのNetAppの推奨アクションを実施できます。サステナビリティダッシュボードの詳細については、link:sustainability-dashboard-overview.html["Sustainabilityダッシュボードの概要"]を参照してください。


NOTE: 持続可能性は、Cloud Volumes ONTAP、AFFシステム（AシリーズおよびCシリーズ）、Eシリーズ、FAS、およびStorageGRIDシステムでサポートされます。

Sustainabilityダッシュボードについては、次のビデオをご覧ください。

video::yNRHeOvbGX8[youtube,width=848,height=480]


[[benefits-of-sustainability]]
== 持続可能性のメリット

サステナビリティには、次のようなメリットがあります。

* 同じ量のデータを保存するストレージデバイスの数を減らして、パフォーマンスを向上させます。
* ストレージシステムの利用率を最適化して、ストレージコストを削減します。
* データセンターで再生可能エネルギーを使用することで、二酸化炭素排出量を削減します。
* エネルギー効率の高い政策を実施することで、エネルギー効率を向上させます。

