---
sidebar: sidebar 
permalink: learn_BlueXP_sustainability.html 
keywords: activeiq, sustainability, sustainability score, sustainability dashboard, bluexp, benefits, ONTAP 
summary: エネルギー消費量を削減し、環境目標に向けた取り組みを可能にする持続可能性に関する情報を提供します。 
---
= 持続可能性の詳細
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
サービスとしての持続可能性により、エネルギー消費量を削減し、環境目標に向かって取り組むことができます。これにより、ストレージシステムを環境に配慮した手法に合わせて調整し、持続可能性の目標を達成できます。

Sustainabilityダッシュボードを使用して、Sustainabilityスコア、およびSustainabilityダッシュボードからの電力、直接炭素、熱の使用量の予測を表示できます。特定のサイトの炭素緩和率を調整できます。持続可能性スコアはクラスタレベルでも確認できます。サステナビリティスコアに基づいて、サステナビリティに対する姿勢を評価し、ネットアップが推奨するアクションを実施してスコアを改善できます。Sustainabilityダッシュボードの詳細については、 link:BlueXP_sustainability_dashboard_overview.html["Sustainabilityダッシュボードの概要"]。


NOTE: 持続可能性は、AFFシステム（AシリーズとCシリーズの両方）、FASシステム、およびCloud Volumes ONTAPでサポートされます。

Sustainabilityダッシュボードについては、次のビデオをご覧ください。

video::yNRHeOvbGX8[youtube,width=848,height=480]


== 持続可能性のメリット

サステナビリティには、次のようなメリットがあります。

* 同じ量のデータを保存するストレージデバイスの数を減らして、パフォーマンスを向上させます。
* ストレージシステムの利用率を最適化して、ストレージコストを削減します。
* データセンターで再生可能エネルギーを使用することで、二酸化炭素排出量を削減します。
* エネルギー効率の高い政策を実施することで、エネルギー効率を向上させます。

