---
sidebar:
  entries:
  - title: Active IQ デジタルアドバイザドキュメント
    url: "/index.html"
  - title: リリースノート
    entries:
    - title: 新機能
      url: "/reference_new_activeiq.html"
    - title: 既知の制限
      url: "/reference_limitations_activeiq.html"
  - title: はじめに
    entries:
    - title: クイックスタート
      url: "/concept_getting_started_2.html"
    - title: Active IQ の機能を理解する
      url: "/concept_understand_activeiq_features.html"
    - title: Active IQ の主要な概念
      url: "/concept_key_terms.html"
    - title: AutoSupport を理解する
      url: "/concept_autosupport.html"
    - title: Active IQ Digital Advisor にログインします
      url: "/task_login_activeiq.html"
  - title: 監視リストをプロビジョニング
    entries:
    - title: 概要
      url: "/concept_overview_dashboard.html"
    - title: 監視リストを作成します
      url: "/task_add_watchlist.html"
    - title: 監視リストを管理します
      url: "/task_manage_watchlists.html"
  - title: 健全性の属性を分析します
    entries:
    - title: 概要
      url: "/concept_overview_wellness.html"
    - title: リスクを確認し、修正措置を手動で実施します
      url: "/task_view_risk_and_take_action.html"
    - title: ハッカーやランサムウェア攻撃に対する保護を強化
      url: "/task_increase_protection_against_hackers_and_Ransomware_attacks.html"
    - title: リスクを確認して承認します
      url: "/task_view_and_acknowledge_risks.html"
    - title: 健全性の履歴を表示します
      url: "/task_view_wellness_history.html"
    - title: Active を使用して自動で軽減できるリスクを表示します IQ Unified Manager または Ansible プレイブック
      url: "/task_view_risks_remediated_unified_manager.html"
    - title: ダウンタイムとデータ損失の可能性を回避します
      url: "/task_avoid_the_downtime_and_possible_data_loss.html"
    - title: ウェルネスレビューメールに登録する
      url: "/task_subscribe_to_wellness_review_email.html"
    - title: ソフトウェアとハードウェアを更新します
      url: "/task_renew_software_and_hardware.html"
    - title: クラスタとノードの健全性を分析します
      url: "/task_analyze_wellness_clusters_and_nodes.html"
  - title: システムの詳細を表示します
    entries:
    - title: インベントリの詳細を表示します
      url: "/task_view_inventory_details.html"
    - title: 価値ある分析情報を確認できます
      url: "/task_view_valuable_insight_widget.html"
    - title: Flex サブスクリプションの容量使用率を表示します
      url: "/task_view_keystone_capacity_utilization.html"
  - title: システム要件をプロアクティブに特定します
    entries:
    - title: 概要
      url: "/concept_overview_planning.html"
    - title: 容量が上限に達しているシステムを特定します
      url: "/task_identify_capacity_system.html"
    - title: ボリュームがいっぱいにならないようにしてシステム停止を回避してください
      url: "/task_avoid_a_volume_filling_up_to_prevent_an_outage.html"
    - title: ソフトウェアとハードウェアを更新します
      url: "/task_renew_software_and_hardware.html"
  - title: 設定の違いを特定
    entries:
    - title: 概要
      url: "/concept_overview_config_drift.html"
    - title: 設定ドリフトテンプレートを追加します
      url: "/task_add_config_drift_template.html"
    - title: 構成ドリフトテンプレートを比較します
      url: "/task_compare_config_drift_template.html"
  - title: ストレージシステムの効率性とパフォーマンスを向上させます
    entries:
    - title: 容量と効率化による削減効果を分析できます
      url: "/task_analyze_storage_efficiency.html"
    - title: ストレージパフォーマンスを分析
      url: "/task_view_performance_graphs.html"
  - title: FabricPool Advisor を使用して、アクセス頻度の低いデータを監視し、階層化する
    url: "/task_monitor_and_tier_inactive_data_with_FabricPool_Advisor.html"
  - title: ストレージシステムの健常性を分析します
    entries:
    - title: 概要
      url: "/concept_understand_health_check_assessment_dashboard.html"
    - title: 健全性チェック評価ダッシュボードの使用を開始します
      url: "/concept_get_started_with_health_check_assessment_dashboard.html"
    - title: サポート契約の更新
      url: "/task_renew_support_contracts_for_your_systems.html"
  - title: アップグレードしてインストールベースを最適化します
    entries:
    - title: ストレージシステムの ONTAP バージョンをアップグレードします
      url: "/task_view_upgrade.html"
    - title: サポートサービスをアップグレードします
      url: "/task_upgrade_support_offering.html"
    - title: Ansible Playbook を使用して、 AFF と FAS のファームウェアを更新してください
      entries:
      - title: AFF および FAS ファームウェアの Ansible Automation パッケージをダウンロードします
        url: "/task_update_AFF_FAS_firmware.html"
      - title: AFF ファームウェアと FAS ファームウェアの Ansible Automation をインストールして実行します パッケージ（熟練ユーザー）
        url: "/task_install_execute_firmware_update_exp_user.html"
      - title: AFF ファームウェアと FAS ファームウェアの Ansible Automation をインストールして実行します パッケージ (
          初心者 )
        entries:
        - title: Web サーバを使用したホストファームウェアファイル
          url: "/task_hosting_firmware_files_using_web_server.html"
        - title: インベントリファイルを操作します
          url: "/concept_working_with_inventory_file.html"
        - title: NetApp Docker イメージを使用して Ansible プレイブックを実行する
          url: "/task_execute_ansible_playbook_using_docker.html"
        - title: Docker を使用せずに Ansible プレイブックを実行する
          url: "/task_execute_ansible_playbook_without_docker.html"
        - title: ファームウェアのインストールを確認
          url: "/task_validate_firmware_installation.html"
        - title: トラブルシューティング、フィードバック、サポート
          url: "/reference_ansible_troubleshoot_feedback_support.html"
  - title: API を使用してデータを統合
    entries:
    - title: 概要
      url: "/concept_overview_API_service.html"
    - title: API にアクセスするためのトークンを生成します
      url: "/task_generate_tokens_API_services.html"
    - title: API を実行するには、 API カタログを使用します
      url: "/task_view_API_catalog.html"
  - title: レポートを生成します
    url: "/task_generate_reports.html"
  - title: よくある質問
    url: reference_aiq_faq.html
  - title: 詳細はこちらをご覧ください
    url: "/concept_get_more_information.html"
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: Active IQ の詳細をご覧ください
      url: https://tv.netapp.com/detail/video/6254074753001/what-can-you-do-with-active-iq
    - title: Active IQ のクイックスタート
      url: concept_getting_started_2.html
    - title: 主な概念
      url: concept_key_terms.html
    - title: 監視リストを作成します
      url: task_add_watchlist.html
  - title: Active IQ を使用します
    links:
    - title: リスクを確認して対処
      url: task_view_risk_and_take_action.html
    - title: 設定の違いを検出
      url: task_compare_config_drift_template.html
    - title: 重要なセキュリティリスクを修正
      url: task_increase_protection_against_hackers_and_Ransomware_attacks.html
    - title: ストレージパフォーマンスを分析
      url: task_view_performance_graphs.html
    - title: レポートを生成します
      url: task_generate_reports.html
  - title: Active IQ を使用して分析します
    links:
    - title: ONTAP のアップグレードに関する推奨事項を確認する
      url: task_view_upgrade.html
    - title: Cloud Manager でストレージ容量を削減
      url: task_monitor_and_tier_inactive_data_with_FabricPool_Advisor.html
    - title: NetApp Keystone フレックスサブスクリプションを使用して容量利用率を表示します
      url: task_view_keystone_capacity_utilization.html
  - title: リソースの追加
    links:
    - title: Active IQ Web ポータル
      url: https://mysupport.netapp.com/myautosupport/home.html
    - title: Active IQ ビデオ
      url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7kWBxqwLYBchpMW4k9Z6Vum
    - title: ネットアップコミュニティ– Active IQ
      url: https://community.netapp.com/t5/Active-IQ-and-AutoSupport/ct-p/autosupport-and-my-autosupport
    - title: Active IQ モバイルアプリケーション（ Android ）
      url: https://play.google.com/store/apps/details?id=com.netapp.aiqda&hl=en_IN&gl=US
    - title: Active IQ モバイルアプリケーション（ iOS ）
      url: https://apps.apple.com/in/app/active-iq-digital-advisor/id1562880322
