---
sidebar: sidebar 
permalink: reference_limitations_activeiq.html 
keywords: limitation, issues, not supported, drawbacks 
summary: に、このリリースの制限事項を示します。 
---
= 既知の制限
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください

次の制限事項があります。

* Data ONTAP 7-Mode ストレージシステムの場合のみ （ 7-Mode を実行している Data ONTAP ストレージシステムがまもなく終了します サポート寿命）
+
** パフォーマンスチャート
** ストレージ効率


* Upgrade Advisor では、 9.0 より前の clustered ONTAP のアップグレードプランはサポートされません。




== 監視リストの編集には、Digital Advisorに反映されるまでに60分かかる場合があります

ウォッチリストを編集しても、Digital Advisorの情報はすぐには更新されません。変更がDigital Advisorに反映されるまでに最大60分かかる場合があります。



== レポートのスケジュール設定中に空のレポートが表示されます

スケジュールされたレポートは、 SupportEdge Advisor または SupportEdge Expert サポート契約がある場合にのみ使用できます。システムが SupportEdge Advisor または SupportEdge Expert サポート契約を締結していない場合は、レポートのスケジュール設定中に空白のレポートが表示されることがあります。



== 承認済みのリスクと未確認のリスクがDigital Advisorに反映されるまでに60分かかる場合があります

承認済みおよび承認済みのリスクのステータスは、Digital Advisorにはすぐに反映されません。変更内容がDigital Advisorと健全性レポートに反映されるまでに最大60分かかる場合があります。
