---
sidebar: sidebar 
permalink: reference_limitations_activeiq.html 
keywords: limitation, issues, not supported, drawbacks 
summary: に、このリリースの制限事項を示します。 
---
= Digital Advisorの既知の制限
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
既知の制限事項は、このリリースの製品でサポートされていないプラットフォーム、デバイス、機能、または製品と正しく相互運用できない機能を特定します。これらの制限事項を慎重に確認してください

次の制限事項があります。

* Data ONTAP 7-Mode ストレージシステムの場合のみ （ 7-Mode を実行している Data ONTAP ストレージシステムがまもなく終了します サポート寿命）
+
** パフォーマンスチャート
** ストレージ効率


* Upgrade Advisor では、 9.0 より前の clustered ONTAP のアップグレードプランはサポートされません。




[[editing-a-watchlist-may-take-60-minutes-to-reflect-in-digital-advisor]]
== 監視リストの編集には、Digital Advisorに反映されるまでに60分かかる場合があります

ウォッチリストを編集しても、Digital Advisorの情報はすぐには更新されません。変更がDigital Advisorに反映されるまでに最大60分かかる場合があります。



[[a-blank-report-is-displayed-while-scheduling-reports]]
== レポートのスケジュール設定中に空のレポートが表示されます

スケジュールされたレポートは、 SupportEdge Advisor または SupportEdge Expert サポート契約がある場合にのみ使用できます。システムが SupportEdge Advisor または SupportEdge Expert サポート契約を締結していない場合は、レポートのスケジュール設定中に空白のレポートが表示されることがあります。



[[acknowledged-and-unacknowledged-risks-may-take-60-minutes-to-reflect-in-digital-advisor]]
== 承認済みのリスクと未確認のリスクがDigital Advisorに反映されるまでに60分かかる場合があります

承認済みおよび承認済みのリスクのステータスは、Digital Advisorにはすぐに反映されません。変更内容がDigital Advisorと健全性レポートに反映されるまでに最大60分かかる場合があります。



[[autosupport-widget-not-available-for-cluster-and-serial-numbers]]
== クラスタ番号とシリアル番号ではAutoSupportウィジェットを使用できません

AutoSupportウィジェットには、クラスタとシリアル番号の検索に関するアラートは表示されません。



[[autosupport-widget-not-able-to-drill-down-to-serial-level-autosupport-details]]
== AutoSupportウィジェットでシリアルレベルのAutoSupportの詳細にドリルダウンできない

AutoSupportの[Reporting]ページで、ステータス、最近送信を停止したシステム、AutoSupportがオフになっているシステムをクリックしても、[Health Check]画面には移動しません。



[[filtering-and-sorting-are-not-available-in-the-inventory-widget]]
== [Inventory]ウィジェットではフィルタとソートは使用できません。

インベントリウィジェットでデータをフィルタしてソートすることはできません。[Filter by]ドロップダウンでONTAP AFF、ONTAP ASA、ONTAP Edge、またはONTAP Selectを選択しても、データは表示されません。
