---
sidebar: sidebar 
permalink: reference_new_activeiq.html 
keywords: what's new, features, new 
summary: リリースの新機能に関する情報を提供します。 
---
= Active IQ デジタルアドバイザの新機能
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
新機能と拡張機能は次のとおりです。



== 2021 年 2 月 24 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== Config Drift

このリリースには、次の機能があります。

* テンプレートの作成時に属性を編集できます。
* AutoSupport セクションのグループ化。
* 構成のドリフトレポートを顧客、サイト、グループ、監視リスト、クラスタ全体にわたって生成またはスケジュール設定する とホスト名です。 link:task_compare_config_drift_template.html["詳細をご確認ください"]。




=== レポート

容量と効率に関するレポートを生成またはスケジュール設定して、システムの容量と Storage Efficiency による削減量に関する詳細情報を表示できます。



== 2021 年 2 月 10 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== StorageGRID

StorageGRID ダッシュボードは、 NextGen API フレームワークを使用して有効にします。

監視リスト、お客様、グループ、サイトレベルの情報を表示するには、 StorageGRID ダッシュボードを使用します。

このリリースには、次の機能があります。

* * インベントリウィジェット： * 選択したレベルで利用可能な StorageGRID システムのインベントリを表示します。
* * ウェルネスウィジェット： * 使用可能なシステムの既存の ARS ルールに基づいて適用される場合は、 StorageGRID に関連するリスクとアクションを含め、すべてのリスクとアクションを表示します。
* * 計画ウィジェット： *
+
** * 容量の追加：既存の容量のしきい値の 70% を超えているグリッドサイトには通知が送信されます。容量のしきい値が 70% を超える可能性がある場合は、サイトのストレージグリッドの容量を 1 、 3 、 6 カ月間追加できます。
** * 契約更新： * ライセンス契約が期限切れになっている、または今後 6 カ月以内に期限が近づいている StorageGRID システムについては、通知が届きます。1 つ以上のシステムを選択して、ネットアップサポートチームに契約更新を申請することができます。


* * グリッドダッシュボード： * グリッドダッシュボードには、選択したグリッドに対する健全性、計画、設定の詳細が表示されます。
* * 構成ウィジェット： * ウィジェットで選択した StorageGRID の基本的な詳細情報を表示します。これには、グリッド名、ホスト名、シリアル番号、モデル、 OS バージョン、お客様名、配送先、連絡先情報などが含まれます。
* * グリッドビューア： * 環境設定 * ウィジェットから * グリッドビューア * リンクをクリックすると、グリッド設定を詳細に表示できます。構成 * ウィジェットから、選択した StorageGRID のサイトの詳細と容量の詳細をダウンロードするには、 * グリッドビューア * 画面で * ダウンロード * ボタンをクリックします。
* * サイトの詳細： * このタブには、各サイトで使用可能なグリッドの概要とストレージノードが表示されます。
* * グリッドサマリ： * 基本情報が含まれます。たとえば、ライセンスタイプ、ライセンス容量、インストールされているノードの数、サポート期間（ライセンス契約終了日）、プライマリ管理ノード、プライマリ管理ノードのプライマリサイトなどです。このタブには、サイト名、および対応するサイトでタグ付けされているストレージノードの数も表示されます。このリリースでは、対応するサイトのストレージノードを表示するためのハイパーリンクをクリックすると、ノード名のリストが表示されます。
* * Capacity Details タブ：グリッドに対して設定された Grid レベルとサイトの容量の詳細が表示されます。インストールされているストレージ容量、使用可能なストレージ容量、合計使用済みストレージ容量、データとメタデータに使用されている容量など、容量の詳細。これらの詳細は、グリッドレベルとサイトレベルの両方で確認できます。




=== FabricPool アドバイザー

FabricPool ダッシュボードに階層データボタンが追加され、 NetApp ® Cloud Manager を使用して低コストのオブジェクトストレージ階層にデータを階層化できるようになりました。



=== クラウド対応ワークロード

ストレージシステム内で使用可能なさまざまなタイプのワークロードを表示して、クラウド対応のワークロードを特定できます。



== 2020 年 12 月 21 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== 健全性チェック評価ダッシュボード

ダッシュボードに次のウィジェットが追加されました。

* 推奨ソフトウェア：このウィジェットには、すべてのソフトウェアとファームウェアのアップグレードおよび通貨に関する推奨事項の統合リストが表示されます。
* 信号消失：このウィジェットは、何らかの理由で AutoSupport データの送信を停止したシステムに関するスコアと情報を提供します。7 日以内にホスト名から AutoSupport データが受信されなかった場合に情報を提供します。




== 2020 年 11 月 12 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== API を使用したデータの統合

Active IQ API を使用して、関心のあるデータを抽出し、会社のワークフローに直接統合できます。 link:concept_overview_API_service.html["詳細はこちら。"]。



=== 健全性 - アップグレードウィジェット

強化された Risk Advisor タブと Upgrade Advisor タブでは、すべてのシステムリスクを表示し、すべてのリスクを軽減するためのアップグレードを計画する際に役立ちます。



=== 健全性チェック評価ダッシュボード

推奨構成ウィジェットがダッシュボードに追加され、リモート管理のリスク、スペアドライブと障害ドライブのリスク、 HA ペアのリスクについて監視しているシステムの数が表示されます。



=== FabricPool アドバイザー

クラスタを監視することで、ストレージの設置面積と関連コストを削減できます。これらのデータは、アクセス頻度の低いローカル階層（アグリゲート）データ、アクセス頻度の低いボリュームデータ、階層化データ、 IDR が有効になっていないデータの 4 つのカテゴリに分類されています。



=== 簡体字中国語および日本語でのローカライズ

Active IQ デジタルアドバイザは、中国語、英語、日本語の 3 言語に対応しています。



=== レポート

Cluster Viewer レポートを生成またはスケジュールして、システムの物理構成と論理構成の詳細情報を表示できます。 link:task_generate_reports.html["詳細をご確認ください"]。



== 2020 年 10 月 15 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== 健全性チェック評価ダッシュボード

Active IQ の健全性チェック評価（ HCA ）ダッシュボードでは、環境全体の状況をまとめて確認できます。健全性チェックのスコアに基づいて、長期的な計画を立て、インストールベースの健全性を高めるために、ストレージシステムを推奨されるネットアップのベストプラクティスに合わせることができます。 link:concept_understand_health_check_assessment_dashboard.html["詳細はこちら。"]。



=== Config Drift

この機能を使用すると、システム構成とクラスタ構成を比較し、設定の差異をほぼリアルタイムで検出できます。 link:task_add_config_drift_template.html["設定のドリフトテンプレートを追加する方法について説明します"]。



=== AutoSupport

AutoSupport データを表示し、詳細を確認できます。



=== 健全性レビューサブスクリプション

システムの健全性ステータスをまとめた E メール通知を月単位で受け取るように登録できます。更新日が近づいているため、インストールベースでネットアップ製品のアップグレードが必要になります。 link:task_subscribe_to_wellness_review_email.html["今すぐサブスクライブ"]。



=== レポート

レポート機能を使用すると、すぐにレポートを生成したり、週単位または月単位でレポートを生成するようにスケジュールしたりできます。 link:task_generate_reports.html["詳細をご確認ください"]。



=== AutoSupport の手動アップロード

手動 AutoSupport アップロードが強化され、ユーザエクスペリエンスが向上しました。アップロードステータスに関する備考の列が追加されました。



=== Keystone ウィジェット

NetApp Keystone Flex サブスクリプションサービスのコミット済み、消費済み、バーストのストレージ容量を監視できます。



== 2020 年 9 月 30 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== Ansible Playbook を使用した AFF および FAS ファームウェア

ドキュメントが強化され、 AFF ファームウェアと FAS ファームウェアの Ansible による自動化パッケージのダウンロード、インストール、実行に関する情報が追加されました。

link:task_update_AFF_FAS_firmware.html["Ansible を使用して AFF と FAS のファームウェアを更新する方法について説明します Playbook"]。



== 2020 年 8 月 18 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== パフォーマンス

パフォーマンスグラフが強化され、ボリュームのパフォーマンスを評価できるようになりました。ノードタブ、クラスタタブ、ローカル階層タブ、ボリュームタブの切り替えは同じ画面で実行できます。 link:task_view_performance_graphs.html["詳細をご確認ください"]。



=== Ansible Playbook を使用した AFF および FAS ファームウェア

AFF および FAS ファームウェア画面が強化され、より良いユーザエクスペリエンスが提供されるようになりました。



== 2020 年 7 月 17 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== パフォーマンス

パフォーマンスグラフが強化され、ローカル階層のパフォーマンスを評価できるようになりました。同じ画面でノードタブ、クラスタタブ、ローカル階層タブの間を移動および切り替えできます。



=== 健康

健全性の属性が強化され、影響を受けるすべてのシステムが表示されるようになりました。対処方法やリスクについて詳細に調べる必要はありません。



== 2020 年 6 月 19 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== インベントリのレポートを生成します

選択した監視リストのレポートを生成し、レポートを最大 5 人の受信者に E メールで送信できるようになりました。 link:task_view_inventory_details.html["詳細をご確認ください"]。



=== パフォーマンス

パフォーマンスグラフが強化され、ストレージシステムのクラスタパフォーマンスを評価できるようになりました。同じ画面でノードタブとクラスタタブの間を移動および切り替えできます。



=== ストレージ効率

Storage Efficiency ウィジェットが強化され、クラスタレベルでストレージ効率と削減量を表示できるようになりました。同じ画面でノードタブとクラスタタブの間を移動および切り替えできます。



=== デフォルトのホームページを更新します

フィードバックをお寄せいただき、 Active IQ のデフォルトのホームページ画面を更新した理由をお知らせいたします。



=== インベントリウィジェットを更新します

インベントリウィジェットが強化され、使いやすい日付形式、プラットフォームのサポート終了用の列、およびバージョンのサポート終了時の列が提供されるようになり、ユーザエクスペリエンスが向上しました。



== 2020 年 5 月 19 日

この更新プログラムには、次の新機能、拡張機能、および変更が含まれています。



=== デフォルトのホームページを設定します

Active IQ のデフォルトのホームページ画面を設定できるようになりました。Active IQ デジタルアドバイザまたは Active IQ クラシックに設定できます。



=== ストレージ効率

AFF システム、 AFF 以外のシステム、またはその両方について、 Snapshot バックアップの有無に関係なく、ストレージシステムの Storage Efficiency 比率と削減量を表示できます。ストレージ効率情報はノードレベルで表示できます。 link:task_analyze_storage_efficiency.html["詳細をご確認ください"]。



=== パフォーマンス

パフォーマンスグラフを使用して、さまざまな重要領域でストレージデバイスのパフォーマンスを評価できます。



=== Ansible Playbook を使用した AFF および FAS ファームウェアのアップグレード

特定されたリスクを軽減し、ストレージシステムを最新の状態に維持するために、ストレージシステムで Ansible を使用して AFF と FAS のファームウェアを更新します。



=== 健全性スコア機能を無効にします

健全性スコア機能は一時的に無効になっており、スコアリングアルゴリズムを改善して全体的なエクスペリエンスを簡素化します。



== 2020 年 4 月 2 日

この更新プログラムには、次の新機能と機能拡張が含まれています。



=== オンボーディングの概要ビデオ

オンボーディングビデオは、 Active IQ デジタルアドバイザのオプションと機能をすばやく理解するのに役立ちます。



=== 健康スコア

健全性スコアを取得すると、高いリスクの数と期限切れの契約数に基づいて、インストールベースの総合スコアをお客様に提供できます。スコアは、「良い」、「普通」、「悪い」のいずれかになります。



=== リスクの概要

リスクの概要には、リスク、リスクの影響、対処方法に関する詳細情報が表示されます。



=== リスクの承認と無視のサポート

リスクを軽減する必要がある場合、または軽減できない場合に、リスクを承認するオプションを提供します。



== 2020 年 3 月 19 日

この更新プログラムには、次の新機能と機能拡張が含まれています。



=== アップグレードワークフロー

アップグレードワークフローを使用して、アップグレードの推奨事項や、ターゲットの ONTAP リリースで使用できる新機能の概要を確認できます。 link:task_view_upgrade.html["詳細をご確認ください"]。



=== 価値ある分析情報

Active IQ およびサポート契約を通じて得られた特典の概要を確認できます。選択したシステムについては、値レポートに過去 1 年間のメリットが統合されています。 link:task_view_valuable_insight_widget.html["今すぐご覧ください"]。



=== 詳細を確認します

より詳細な情報を提供します。これは、データを詳細に分析し、必要に応じて集計された情報の構成を即座に把握するための強力な方法です。



=== 容量の追加

容量を超えているシステムや容量の 90% に近づいているシステムをプロアクティブに特定し、容量の拡張を申請できます。



== 2020 年 2 月 29 日

この更新プログラムには、次の新機能と機能拡張が含まれています。



=== 強化されたユーザインターフェイス

最新の Active IQ デジタルアドバイザダッシュボードでは、パーソナライズされたエクスペリエンスを提供します。直感的な操作で、ダッシュボード、ウィジェット、画面全体をスムーズかつシームレスにナビゲーションできます。一体型のエクスペリエンスを提供します。比較、関係、傾向について説明します。さまざまなダッシュボードで提示されるデータに基づいて、重要な関係や意味のある違いを検出して検証するのに役立つ分析情報を提供します。



=== カスタマイズ可能なダッシュボード

1 つ以上のページや画面でデータに関する重要な分析情報を提供し、システムを一目で監視できるようにします。最大 10 個のダッシュボードを作成して、ビジネス上の意思決定を効率的に行うこともできます。

link:concept_overview_dashboard.html["詳細はこちら。"]。



=== Active IQ Unified Manager を使用してリスクを軽減

Active IQ Unified Manager を使用して、リスクを表示して修正できます。 link:task_view_risks_remediated_unified_manager.html["詳細をご確認ください"]。



=== 健康

次の 6 つのウィジェットに分類されるストレージシステムのステータスに関する詳細情報を表示します。

* パフォーマンスと効率性
* 可用性と保護
* 容量
* 設定
* セキュリティ
* 契約更新


を参照してください link:concept_overview_wellness.html["健全性の属性を分析します"] 詳細：



=== よりスマートで高速な検索

単一システムビューを使用して、シリアル番号、システム ID 、ホスト名、サイト名、グループ名、クラスタ名などのパラメータを検索できます。また、システムのグループを検索することもできます。また、システムのグループごとに、お客様名、サイト名、またはグループ名で検索することもできます。
