---
sidebar: sidebar 
permalink: reference_new_activeiq.html 
keywords: 'what"s new, features, new' 
summary: リリースの新機能に関する情報を提供します。 
---
= Active IQ デジタルアドバイザの新機能
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
NetApp Active IQ デジタルアドバイザでは、次の機能と拡張機能が導入されました。



== 2022年6月22日



=== StorageGRID

StorageGRID 用の情報ライフサイクル管理（ILM）は、グリッドビューアに含まれています。



=== クラウドに関する推奨事項

SnapMirrorデータレプリケーションを使用してNetApp Cloud Volumes ONTAP 、NetApp Cloud Volumes Service 、およびNetApp Cloud Backup（旧称AltaVault ）に移動できるワークロードとそのボリュームに関する推奨事項を提供します。 link:task-informed-decisions-based-on-cloud-recommendations.html["詳細をご確認ください"]。



=== レポート

* 生成済みのレポートに定義された条件を使用してレポートを生成できるようになりました。
* 失敗したレポートの生成を3回試行できるようになりました。
* 生成されたレポートの保持期間が3日から90日に延長されました。




== 2022年6月1日



=== 在庫

* Inventoryでシステムの営業担当者情報を確認できるようになりました。
* Astra Control Centerシステムがインベントリで利用できるようになりました。




== 2022年5月12日



=== StorageGRID

StorageGRID の容量レポートと容量レポートには、容量の指標も表示されます。



=== Cluster Viewer （クラスタビューア）

Cluster Viewerに、クラスタのSnapMirror（データ保護）の概要が追加されました。



=== アップグレードワークフロー

アップグレードワークフローを使用して、ターゲットのEシリーズリリースで利用できるアップグレードの推奨事項と新機能の概要を確認できるようになりました。



=== 健康

* Ansible Playbookは、ソフトウェア構成のリスクを軽減するために強化されています。
* フィルタが健全性のアクションとリスクに統合されました。




== 2022 年 4 月 7 日



=== 健康

* 最新のオペレーティングシステムバージョンとサポート契約およびサポート終了に関する 6 カ月の KPI の重要な推奨事項の採点は、解決の緊急性の低下に合わせて削減されました。
* リモート管理と HA ペア（推奨構成）に関する主な推奨事項が更新され、カスタマーセルフサービス用のネットアップサポートサイトへの URL が追加されました。




== 2022 年 3 月 31 日



=== StorageGRID

グリッドビューアでテナントとバケットの情報を表示できます。



== 2022 年 3 月 24 日



=== 健全性チェックのダッシュボード

* Health Assessment Executive Summary PPT の機能強化とバグ修正。
* 推奨される最小バージョンアップグレードプランを生成する機能。
* 健全性チェックタイルの機能強化により、各 KPI で注意が必要なノード数を特定。




=== StorageGRID

グリッド設定の詳細は、グリッドビューアで確認できます。



=== クラウドマネージャ

Cloud Manager ユーザは、 Active IQ の既存の機能と同様に、必要に応じて新しいタブで Active IQ リンクを開くことができます。



== 2022 年 1 月 12 日



=== Config Drift

* テンプレートを複製して、元のテンプレートのコピーを作成できます。
* ゴールデンテンプレートは、これらのテンプレートに読み取り専用またはフルアクセスして、他の使用権のあるユーザと共有できます。link:task_manage_template.html["詳細をご確認ください"]。




== 2021 年 12 月 15 日



=== レポート

* * Cluster Viewer Report * ：このレポートには、 1 つまたは複数のクラスタに関する情報が顧客レベルと監視リストレベルで表示されます。Cluster Viewer レポートを使用して、 1 つのファイル内のすべての情報をダウンロードできます。このレポートは、ノードが 100 個までの監視リストに対してのみ生成できます。
* * パフォーマンスレポート * ：このレポートは、監視リストレベルで、クラスタ、ノード、ローカル階層（アグリゲート）、ボリュームのパフォーマンスに関する情報を 1 つの zip ファイルにまとめたものです。各 zip ファイルには、単一のクラスタのパフォーマンスデータが含まれており、各クラスタのデータの分析に役立ちます。このレポートは、ノードが 100 個までの監視リストに対してのみ生成できます。




=== E シリーズシステムとの統合

Active IQ では、選択した E シリーズシステムの容量の詳細とパフォーマンスグラフを表示できます。



== 2021 年 11 月 18 日



=== ストレージ効率

NetApp Cloud Insights で管理および監視されているノードのストレージ効率の詳細を表示できます。



== 2021 年 11 月 11 日



=== 健全性チェックのダッシュボード

* 健全性チェックタイルにアイコンが追加されました。このアイコンは、 SupportEdge Advisor および SupportEdge Expert サポートサービスを提供するシステムにのみ適用されます。この機能強化は、「ソフトウェアの通貨とファームウェアの通貨」セクション、「推奨構成」、「ベストプラクティス」の推奨ソフトウェアに適用されました。
* Active IQ デジタルアドバイザの [ レポート ] 画面に、社内ユーザと社外（お客様とパートナー）ユーザのための機密データバナーを追加しました。




=== 健全性とアップグレードウィジェット

E シリーズのアップグレードに関する推奨事項と、ウェルネスアクション履歴の列にリスクトリガー日が追加されたダッシュボードが強化されました。



=== Cluster Viewer （クラスタビューア）

Cluster Viewer Stack Visualization モジュールが強化され、 Zoom In/Zoom Out and Save Image 機能が追加されました。



=== ストレージ効率

NetApp Cloud Insights で管理および監視されるシステムのストレージ効率の詳細を表示できます。



== 2021 年 10 月 14 日



=== Ansible のインベントリ

地域およびサイトレベルで、 .yml および .ini ファイル形式で Ansible インベントリファイルを生成できるようになりました。 link:task_view_inventory_details.html["詳細をご確認ください"]。



=== Inactive Data Reporting （ IDR ）

FabricPool Advisor の画面で、 Inactive Data Reporting （ IDR ）をアクティブ化してアグリゲートを監視し、 Ansible プレイブックを生成できます。 link:task_monitor_and_tier_inactive_data_with_FabricPool_Advisor.html["詳細はこちら。"]



=== ドリフトタイムラインレポート

過去 90 日間の AutoSupport データを比較して、ドリフトタイムラインレポートを生成できます。 link:task_generate_drift_timeline_report.html["詳細をご確認ください"]。



=== 準拠システムの切り替え

健全性チェックダッシュボードが強化され、 OS の最小数と最新バージョンの切り替えが可能になりました。これにより、システムが準拠しており、推奨バージョンと最新バージョンの最小要件に準拠していないことを確認できます。



=== 主な推奨事項の概要

ヘルスチェックダッシュボードでは、主要な推奨事項の上位 5 つの概要を確認できます。



=== ネットアップの Cloud Volumes ONTAP および E シリーズプラットフォーム用のタブ

健全性チェックダッシュボードが強化され、 Cloud Volumes ONTAP ** および E シリーズのタブではヘルスチェック KPI やそれらのプラットフォームの詳細を表示できるようになりました。

「 ONTAP 」のタブも、現在有効になっている他のプラットフォームとともに追加されています。



=== 容量

NetApp Cloud Volumes ONTAP システムの容量の詳細は Active IQ で確認できます。



=== レポート

レポートスケジュールは 12 カ月に延長されました。また、スケジュールレポートの有効期限が近づいたときに通知が送信されます。



== 2021 年 9 月 30 日



=== お客様の条件を満たすバージョン

お客様限定バージョンは、サポートアカウントマネージャ（ SAM ）がお客様のインストールベースの一部を管理するのに役立ちます。このベースには、次の要件を満たすアプリケーションが含まれます。

* ONTAP の以前のバージョンと、サポートされない場合もあります
* または、特定の OS バージョンを使用することがテストおよび認定されたお客様のインストールベース。




=== テクニカルケースのワークフロー

ダッシュボードとドリルダウン画面の両方で、データチャートと折れ線グラフにグラフィカルな機能強化が施されています。また、棒グラフでそのデータを表示することもできます。折れ線グラフウィンドウでは、これらのユーザーインターフェイスの [ オープン ] 、 [ クローズ済み ] 、 [ 合計 ] の各ケースのグラフを表示、選択、選択解除できます。



=== パフォーマンスグラフ

パフォーマンスグラフは、 CSV 形式に加えて、 PNG 形式および JPG 形式でダウンロードできるようになりました。



=== サポート終了（ EOS ）コントローラが 12 カ月以上ある

ヘルスチェックダッシュボードが強化され、 12 カ月を超える EOS があるコントローラを表示するタブが追加されました。



== 2021 年 9 月 16 日



=== 健康

* ランサムウェア防御ウィジェットは、スタンドアロンウィジェットではなくウェルネスワークフローの一部になりました。
* Wellness Review の E メールでは、更新ではなくランサムウェア防御に関する情報を確認できます。




=== 容量

Active IQ では、 NetApp ONTAP ® Select システムの容量に関する詳細を確認できます。



=== Cluster Viewer （クラスタビューア）

Cluster Viewer の表示タブで、ケーブル接続の問題やその他のエラーを確認できます。



== 2021 年 9 月 6 日



=== StorageGRID

* View AutoSupport ： StorageGRID と基盤のノードの AutoSupport ログを表示します。
* StorageGRID アプライアンスの詳細：ノードタイプ、アプライアンスモデル、ドライブサイズ、ドライブタイプ、 RAID モードなど、 StorageGRID アプライアンスの詳細を表示します。 グリッドビューアのグリッドインベントリセクションなどで行います。
* 更新：グリッドと、更新が予定されている基盤のノードのリストを表示します。
* E シリーズ SANtricity のリスク：グリッドの「ダッシュボード - ウェルネス」セクションで、基盤となるノードの E シリーズ SANtricity のリスクを確認できます。




=== 容量の予測

容量予測ウィジェットが更新され、システムの再構成を改善するアルゴリズムが追加されました。 link:reference_aiq_faq.html#capacity["詳細はこちら。"]。



== 2021 年 8 月 26 日



=== Active IQ デジタルアドバイザモバイルアプリケーション

Active IQ デジタルアドバイザモバイルアプリケーションで生体認証を有効にできるようになりました。認証に使用できるオプションは、お使いの携帯電話でサポートされている機能によって異なります。

アプリケーションをダウンロードして、詳細を確認してください。link:https://play.google.com/store/apps/details?id=com.netapp.aiqda&hl=en_IN&gl=US["Active IQ デジタルアドバイザモバイルアプリケーション（ Android ）"]
link:https://apps.apple.com/in/app/active-iq-digital-advisor/id1562880322["Active IQ デジタルアドバイザモバイルアプリケーション（ iOS ）"]



=== 健康

ウェルネスウィジェットには、 Ransomware Defense 属性が追加されています。ランサムウェアの検出、防止、リカバリに関連するリスクや対処方法を確認できるようになりました。



== 2021 年 8 月 16 日



=== 健全性のレビュー

これで、オンデマンドレポートを生成できるようになりました。さらに、最後にスケジュールされたレポートは、 [Wellness Review Subscription] 画面からダウンロードできます。



=== 在庫

Grid Inventory タブでは、ノードの詳細をサイトレベルに基づいて展開および縮小可能な形式で表示できるようになりました。



=== 混在モデルクラスタフラグ

クラスタに複数のハードウェアモデルが混在している場合は、クラスタ全体に適用されている OS バージョンが、すべてのノードで使用できるバージョンになります。そのため、最新のハードウェアモデルの一部のノードの OS バージョンが、適切な場所から旧バージョンになる可能性があります。これらの混在モデルクラスタをより見やすくするために、「混在モデル」アイコンを適用しました。



=== 推奨される構成 / Storage Virtual Machine （ SVM ）の健常性：ボリュームレベルの概要

SVM テーブルの青い [ ボリュームの概要 ] ボックスをクリックすると、ポップアップに、特定のシリアル番号または物理ノードにホストまたは接続されているボリュームに関する詳細情報が表示されます。



== 2021 年 7 月 12 日



=== システムファームウェア

ONTAP のメジャーバージョンおよびパッチバージョンと一緒に出荷されたシステムファームウェアに関する情報を確認できるようになりました。この機能には、 [ クイックリンク ] メニューからアクセスできます。



=== 健全性チェックのダッシュボード

* 健全性チェックのダッシュボードが強化され、 SupportEdge Advisor でサポートされないシステムについては青のバナーがユーザに表示されるようになりました。また、 SupportEdge Expert は健全性スコアの計算時に考慮されません。
* 推奨される構成ウィジェットが拡張され、 Storage VM （ SVM ）で失敗したチェックの詳細な分析ができるようになりました。また、リスクごとに推奨される対処方法を確認できます。
* クラスタ内のすべてのノードで、異なるハードウェアモデルを使用して構成された推奨ターゲットの ONTAP バージョンが同じになりました。ターゲットのバージョンはすべてのノードでサポートされます。
* コントローラ、ディスク、シェルフの EOS タイムラインを PVR で購入できるようになりました。購入した PVR の日付と延長期間の詳細は、サポート終了ウィジェットで確認できます。PVR の詳細も EOSL レポートの一部として提供されます。




=== 在庫

詳細なインベントリページでは、ハードウェア、ソフトウェア、および返却できないディスクに関するサポート契約の終了日を確認できます。



=== サポートサービスのアップグレード

* ユーザインターフェイスが強化され、 Active IQ で登録している特定のサポートサービスが表示されるようになりました。
* システムダッシュボードからサポートサービスサブスクリプションのアップグレードを申請して、より多くの機能にアクセスできるようになりました。 link:task_upgrade_support_offering.html["詳細をご確認ください"]。




== 2021 年 6 月 25 日



=== Flex サブスクリプションウィジェット

* ONTAP コレクタで容量の使用状況に関するデータを取得するように選択している場合は、 [ 共有 ] タブと [ ディスク ] タブでファイル共有とディスクの詳細を表示できます。コミット済み容量が上限に近づいていることを確認すると、ストレージスペースを節約できます。
* Keystone - 容量利用率ダッシュボードに表示され、請求に使用される容量が論理容量に基づいて計算されるようになりました。




== 2021 年 6 月 17 日



=== レポート

Storage VM 内のすべてのボリュームについて、曜日、週、または月に応じてアグリゲートボリュームのパフォーマンスレポートを生成できるようになりました。



=== 健全性確認の E メールです

健全性レビューの E メールに、健全性チェックとアップグレード操作のサポートと権限に関する情報が記載されるようになりました。



=== アップグレードワークフロー

* ユーザインターフェイスが強化され、情報の表形式が表示されるようになりました。
* ONTAP バージョンのサポート終了に関する情報を ［ アップグレードの詳細 ］ 画面で確認できるようになりました。




=== Config Drift

* Config Drift が 200 以上の AutoSupport セクションをサポートするようになりました。これにより、ゴールデンテンプレートの作成と、顧客、サイト、グループ、監視リスト、クラスタ、 および host です。
* 設定のずれを使用すると、設定のドリフトレポートのペイロードに含まれる Ansible の Playbook を使用して、違いを軽減できます。




=== 健全性チェックのダッシュボード

この機能が強化され、 Storage VM （ SVM ）と事前定義されたリスクカタログを比較してギャップを評価し、関連する対処方法を推奨できるようになりました。



== 2021 年 6 月 9 日



=== 健全性チェックのダッシュボード

ヘルススコアが計算されたシステムの数を表示できるようになりました。この拡張機能は、健全性チェックダッシュボードのすべての属性に適用されます。



== 2021 年 5 月 20 日



=== 容量追加リクエストのためのドリフトチャット

容量追加リクエストをリアルタイムでサポートするには、ダッシュボードから直接販売員とチャットします。 link:task_identify_capacity_system.html["詳細をご確認ください"]。



== 2021 年 4 月 29 日

* ハッカーやランサムウェア攻撃からシステムを保護する方法をご紹介します。 link:task_increase_protection_against_hackers_and_Ransomware_attacks.html["詳細をご確認ください"]。
* ダウンタイムを回避し、データ損失を回避できます。 link:task_avoid_the_downtime_and_possible_data_loss.html["詳細をご確認ください"]。
* ボリュームがいっぱいにならないようにしてシステム停止を回避する方法をご確認ください。 link:task_avoid_a_volume_filling_up_to_prevent_an_outage.html["詳細をご確認ください"]。




== 2021 年 4 月 7 日



=== 監視リスト

Active IQ デジタルアドバイザに初めてアクセスするときは、ダッシュボードの代わりにウォッチリストを作成する必要があります。また、各種の監視リストのダッシュボードを表示したり、既存の監視リストの詳細を編集したり、監視リストを削除したりすることもできます。



== 2021 年 2 月 24 日



=== Config Drift

このリリースには、次の機能があります。

* テンプレートの作成時に属性を編集できます。
* AutoSupport セクションのグループ化。
* 構成のドリフトレポートを顧客、サイト、グループ、監視リスト、クラスタ全体にわたって生成またはスケジュール設定する とホスト名です。 link:task_compare_config_drift_template.html["詳細をご確認ください"]。




=== レポート

容量と効率に関するレポートを生成またはスケジュール設定して、システムの容量と Storage Efficiency による削減量に関する詳細情報を表示できます。



== 2021 年 2 月 10 日



=== StorageGRID

StorageGRID ダッシュボードは、 NextGen API フレームワークを使用して有効にします。

監視リスト、お客様、グループ、サイトの各レベルで情報を表示するには、 StorageGRID ダッシュボードを使用します。

このリリースには、次の機能があります。

* * インベントリウィジェット： * 選択したレベルで利用可能な StorageGRID システムのインベントリを表示します。
* * ウェルネスウィジェット： * 使用可能なシステムの既存の ARS ルールに基づいて適用される場合は、 StorageGRID に関連するリスクとアクションを含め、すべてのリスクとアクションを表示します。
* * 計画ウィジェット： *
+
** * 容量の追加：既存の容量のしきい値の 70% を超えているグリッドサイトには通知が送信されます。容量のしきい値が 70% を超える可能性がある場合は、サイト内の StorageGRID ID に対して今後 1 カ月、 3 カ月、 6 カ月間の容量を追加することもできます。
** * 契約更新： * ライセンス契約が期限切れになっている、または今後 6 カ月以内に期限が近づいている StorageGRID システムについては、通知が届きます。1 つ以上のシステムを選択して、ネットアップサポートチームに契約更新を申請することができます。


* * グリッドダッシュボード： * グリッドダッシュボードには、選択したグリッドに対する健全性、計画、設定の詳細が表示されます。
* * 構成ウィジェット： * ウィジェットで選択した StorageGRID の基本的な詳細情報を表示します。これには、グリッド名、ホスト名、シリアル番号、モデル、 OS バージョン、お客様名、配送先、連絡先情報などが含まれます。
* * グリッドビューア： * 環境設定 * ウィジェットから * グリッドビューア * リンクをクリックすると、グリッド設定を詳細に表示できます。構成 * ウィジェットから、選択した StorageGRID のサイトの詳細と容量の詳細をダウンロードするには、 * グリッドビューア * 画面で * ダウンロード * ボタンをクリックします。
* * サイトの詳細： * このタブには、各サイトで使用可能なグリッドの概要とストレージノードが表示されます。
* * グリッドサマリ： * 基本情報が含まれます。たとえば、ライセンスタイプ、ライセンス容量、インストールされているノードの数、サポート期間（ライセンス契約終了日）、プライマリ管理ノード、プライマリ管理ノードのプライマリサイトなどです。このタブには、サイト名、および対応するサイトでタグ付けされているストレージノードの数も表示されます。このリリースでは、対応するサイトのストレージノードを表示するためのハイパーリンクをクリックすると、ノード名のリストが表示されます。
* * Capacity Details タブ：グリッドに対して設定された Grid レベルとサイトの容量の詳細が表示されます。インストールされているストレージ容量、使用可能なストレージ容量、合計使用済みストレージ容量、データとメタデータに使用されている容量など、容量の詳細。これらの詳細は、グリッドレベルとサイトレベルの両方で確認できます。




=== FabricPool アドバイザー

FabricPool ダッシュボードに階層データボタンが追加され、 NetApp Cloud Manager を使用して低コストのオブジェクトストレージ階層にデータを階層化できるようになりました。



=== クラウド対応ワークロード

ストレージシステム内で使用可能なさまざまなタイプのワークロードを表示して、クラウド対応のワークロードを特定できます。



== 2020 年 12 月 21 日



=== 健全性チェックのダッシュボード

ダッシュボードに次のウィジェットが追加されました。

* 推奨ソフトウェア：このウィジェットには、すべてのソフトウェアとファームウェアのアップグレードおよび通貨に関する推奨事項の統合リストが表示されます。
* 信号消失：このウィジェットは、何らかの理由で AutoSupport データの送信を停止したシステムに関するスコアと情報を提供します。7 日以内にホスト名から AutoSupport データが受信されなかった場合に情報を提供します。




== 2020 年 11 月 12 日



=== API を使用したデータの統合

Active IQ API を使用して、関心のあるデータを抽出し、会社のワークフローに直接統合できます。 link:concept_overview_API_service.html["詳細はこちら。"]。



=== 健全性 - アップグレードウィジェット

強化された Risk Advisor タブと Upgrade Advisor タブでは、すべてのシステムリスクを表示し、すべてのリスクを軽減するためのアップグレードを計画する際に役立ちます。



=== 健全性チェックのダッシュボード

推奨構成ウィジェットがダッシュボードに追加され、リモート管理のリスク、スペアドライブと障害ドライブのリスク、 HA ペアのリスクについて監視しているシステムの数が表示されます。



=== FabricPool アドバイザー

クラスタを監視することで、ストレージの設置面積と関連コストを削減できます。これらのデータは、アクセス頻度の低いローカル階層（アグリゲート）データ、アクセス頻度の低いボリュームデータ、階層化データ、 IDR が有効になっていないデータの 4 つのカテゴリに分類されています。



=== 簡体字中国語および日本語でのローカライズ

Active IQ デジタルアドバイザは、中国語、英語、日本語の 3 言語に対応しています。



=== レポート

Cluster Viewer レポートを生成またはスケジュールして、システムの物理構成と論理構成の詳細情報を表示できます。 link:task_generate_reports.html["詳細をご確認ください"]。



== 2020 年 10 月 15 日



=== 健全性チェックのダッシュボード

Active IQ 健全性チェックダッシュボードでは、環境全体のポイントインタイムレビューを実施できます。健全性チェックのスコアに基づいて、長期的な計画を立て、インストールベースの健全性を高めるために、ストレージシステムを推奨されるネットアップのベストプラクティスに合わせることができます。 link:concept_understand_health_check_assessment_dashboard.html["詳細はこちら。"]。



=== Config Drift

この機能を使用すると、システム構成とクラスタ構成を比較し、設定の差異をほぼリアルタイムで検出できます。 link:task_add_config_drift_template.html["設定のドリフトテンプレートを追加する方法について説明します"]。



=== AutoSupport

AutoSupport データを表示し、詳細を確認できます。



=== 健全性レビューサブスクリプション

システムの健全性ステータスをまとめた E メール通知を月単位で受け取るように登録できます。更新日が近づいているため、インストールベースでネットアップ製品のアップグレードが必要になります。 link:task_subscribe_to_wellness_review_email.html["今すぐサブスクライブ"]。



=== レポート

レポート機能を使用すると、すぐにレポートを生成したり、週単位または月単位でレポートを生成するようにスケジュールしたりできます。 link:task_generate_reports.html["詳細をご確認ください"]。



=== AutoSupport の手動アップロード

手動 AutoSupport アップロードが強化され、ユーザエクスペリエンスが向上しました。アップロードステータスに関する備考の列が追加されました。



=== Flex サブスクリプションウィジェット

NetApp Keystone Flex サブスクリプションサービスのコミット済み、消費済み、バーストのストレージ容量を監視できます。



== 2020 年 9 月 30 日



=== Ansible Playbook を使用した AFF および FAS ファームウェア

ドキュメントが強化され、 AFF ファームウェアと FAS ファームウェアの Ansible による自動化パッケージのダウンロード、インストール、実行に関する情報が追加されました。

link:task_update_AFF_FAS_firmware.html["Ansible を使用して AFF と FAS のファームウェアを更新する方法について説明します Playbook"]。



== 2020 年 8 月 18 日



=== パフォーマンス

パフォーマンスグラフが強化され、ボリュームのパフォーマンスを評価できるようになりました。ノードタブ、クラスタタブ、ローカル階層タブ、ボリュームタブの切り替えは同じ画面で実行できます。 link:task_view_performance_graphs.html["詳細をご確認ください"]。



=== Ansible Playbook を使用した AFF および FAS ファームウェア

AFF および FAS ファームウェア画面が強化され、より良いユーザエクスペリエンスが提供されるようになりました。



== 2020 年 7 月 17 日



=== パフォーマンス

パフォーマンスグラフが強化され、ローカル階層のパフォーマンスを評価できるようになりました。同じ画面でノードタブ、クラスタタブ、ローカル階層タブの間を移動および切り替えできます。



=== 健康

健全性の属性が強化され、影響を受けるすべてのシステムが表示されるようになりました。対処方法やリスクについて詳細に調べる必要はありません。



== 2020 年 6 月 19 日



=== インベントリのレポートを生成します

選択した監視リストのレポートを生成し、レポートを最大 5 人の受信者に E メールで送信できるようになりました。 link:task_view_inventory_details.html["詳細をご確認ください"]。



=== パフォーマンス

パフォーマンスグラフが強化され、ストレージシステムのクラスタパフォーマンスを評価できるようになりました。同じ画面でノードタブとクラスタタブの間を移動および切り替えできます。



=== ストレージ効率

Storage Efficiency ウィジェットが強化され、クラスタレベルでストレージ効率と削減量を表示できるようになりました。同じ画面でノードタブとクラスタタブの間を移動および切り替えできます。



=== デフォルトのホームページを更新します

フィードバックをお寄せいただき、 Active IQ のデフォルトのホームページ画面を更新した理由をお知らせいたします。



=== インベントリウィジェットを更新します

インベントリウィジェットが強化され、使いやすい日付形式、プラットフォームのサポート終了用の列、およびバージョンのサポート終了時の列が提供されるようになり、ユーザエクスペリエンスが向上しました。



== 2020 年 5 月 19 日



=== デフォルトのホームページを設定します

Active IQ のデフォルトのホームページ画面を設定できるようになりました。Active IQ デジタルアドバイザまたは Active IQ クラシックに設定できます。



=== ストレージ効率

AFF システム、AFF以外のシステム、またはその両方のSnapshotコピーがある場合とない場合のストレージシステムの削減率および削減量を表示できます。ストレージ効率情報はノードレベルで表示できます。 link:task_analyze_storage_efficiency.html["詳細をご確認ください"]。



=== パフォーマンス

パフォーマンスグラフを使用して、さまざまな重要領域でストレージデバイスのパフォーマンスを評価できます。



=== Ansible Playbook を使用した AFF および FAS ファームウェアのアップグレード

特定されたリスクを軽減し、ストレージシステムを最新の状態に維持するために、ストレージシステムで Ansible を使用して AFF と FAS のファームウェアを更新します。



=== 健全性スコア機能を無効にします

健全性スコア機能は一時的に無効になっており、スコアリングアルゴリズムを改善して全体的なエクスペリエンスを簡素化します。



== 2020 年 4 月 2 日



=== オンボーディングの概要ビデオ

オンボーディングビデオは、 Active IQ デジタルアドバイザのオプションと機能をすばやく理解するのに役立ちます。



=== 健康スコア

健全性スコアを取得すると、高いリスクの数と期限切れの契約数に基づいて、インストールベースの総合スコアをお客様に提供できます。スコアは、「良い」、「普通」、「悪い」のいずれかになります。



=== リスクの概要

リスクの概要には、リスク、リスクの影響、対処方法に関する詳細情報が表示されます。



=== リスクの承認と無視のサポート

リスクを軽減する必要がある場合、または軽減できない場合に、リスクを承認するオプションを提供します。



== 2020 年 3 月 19 日



=== アップグレードワークフロー

アップグレードワークフローを使用して、アップグレードの推奨事項や、ターゲットの ONTAP リリースで使用できる新機能の概要を確認できます。 link:task_view_upgrade.html["詳細をご確認ください"]。



=== 価値ある分析情報

Active IQ およびサポート契約を通じて得られた特典の概要を確認できます。選択したシステムについては、値レポートに過去 1 年間のメリットが統合されています。 link:task_view_valuable_insight_widget.html["今すぐご覧ください"]。



=== 詳細を確認します

より詳細な情報を提供します。これは、データを詳細に分析し、必要に応じて集計された情報の構成を即座に把握するための強力な方法です。



=== 容量の追加

容量を超えているシステムや容量の 90% に近づいているシステムをプロアクティブに特定し、容量の拡張を申請できます。



== 2020 年 2 月 29 日



=== 強化されたユーザインターフェイス

最新の Active IQ デジタルアドバイザダッシュボードでは、パーソナライズされたエクスペリエンスを提供します。直感的な操作で、ダッシュボード、ウィジェット、画面全体をスムーズかつシームレスにナビゲーションできます。一体型のエクスペリエンスを提供します。比較、関係、傾向について説明します。さまざまなダッシュボードで提示されるデータに基づいて、重要な関係や意味のある違いを検出して検証するのに役立つ分析情報を提供します。



=== カスタマイズ可能なダッシュボード

1 つ以上のページや画面でデータに関する重要な分析情報を提供し、システムを一目で監視できるようにします。最大 10 個のダッシュボードを作成して、ビジネス上の意思決定を効率的に行うこともできます。

link:concept_overview_dashboard.html["詳細はこちら。"]。



=== Active IQ Unified Manager を使用してリスクを軽減

Active IQ Unified Manager を使用して、リスクを表示して修正できます。 link:task_view_risks_remediated_unified_manager.html["詳細をご確認ください"]。



=== 健康

次の 6 つのウィジェットに分類されるストレージシステムのステータスに関する詳細情報を表示します。

* パフォーマンスと効率性
* 可用性と保護
* 容量
* 設定
* セキュリティ
* 契約更新


を参照してください link:concept_overview_wellness.html["健全性の属性を分析します"] 詳細：



=== よりスマートで高速な検索

単一システムビューを使用して、シリアル番号、システム ID 、ホスト名、サイト名、グループ名、クラスタ名などのパラメータを検索できます。また、システムのグループを検索することもできます。また、システムのグループごとに、お客様名、サイト名、またはグループ名で検索することもできます。
