---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: renew, hardware, software 
summary: ストレージシステムのソフトウェアとハードウェアを更新するための情報を提供します。 
---
= 容量と Storage Efficiency による削減効果を分析できます
:toc: macro
:hardbreaks:
:toclevels: 1
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
システムの容量の詳細および Storage Efficiency による削減効果を表示して、適切な処理を実行できます。容量とストレージ効率の情報は、クラスタレベルまたはノードレベルで表示できます。


NOTE: この機能は E シリーズシステムではサポートされません。

容量のダッシュボードには、システムの容量の詳細と容量予測が表示されます。容量予測では、過去の容量情報を使用して各システムの利用率を特定します。使用容量と割り当て容量の履歴データ（使用可能な場合は 1 年分のデータ）に基づいて、アルゴリズムは各システムの現在の使用率を考慮し、今後 1 ～ 6 か月にわたってシステムの使用率の予測を生成します。

Storage Efficiency ダッシュボードには、 ONTAP 9.1 以降を実行しているストレージシステムのストレージ効率化率、使用済み論理スペース、使用済み物理スペース、および削減された合計データが表示されます。AFF システム、 AFF 以外のシステム、またはその両方で、 Snapshot バックアップの有無に応じて削減率と削減率を確認できます。お客様のストレージ全体での削減量は、ボリュームの重複排除、ボリュームの圧縮、コンパクション、 FlexClone ボリューム、 Snapshot バックアップなどの効率化機能ごとに確認できます。また、削減比率が最も高い上位 5 つのストレージシステムを表示することもできます。

video::8Ge3_0qlyxA[youtube, width=848,height=480]
.手順
. 左側のペインで、 * 容量と効率 * をクリックします。
+
デフォルトでは、 * 容量 * タブが選択されています。

. クラスタレベルおよびノードレベルで容量の詳細を表示します。
+
.. ノードレベルの容量予測を表示します。
+
ONTAP システムについては、 Cluster Viewer で物理容量に関する情報を確認できます。

.. 容量の追加 * をクリックして、ネットアップまたはパートナーに容量を追加する通知を送信します。


. ストレージシステムの Storage Efficiency およびデータ削減量を表示します。
+
.. ストレージシステムのストレージ容量削減比率が平均ストレージ容量削減比率を上回る場合は、「 * ユーザ事例を共有」をクリックして、実施したベストプラクティスをお知らせください。
.. ストレージシステムのストレージ容量削減比率が平均ストレージ容量削減比率より低い場合は、「 * お問い合わせ * 」をクリックして、ストレージシステムの構成をお知らせください。



