---
sidebar: sidebar 
permalink: task_subscribe_to_wellness_review_email.html 
keywords: wellness, wellness review subscription, unsubscribe, supportedge expert, supportedge advisor 
summary:  
---
= Digital Advisorからのストレージ システムの健全性に関する通知を購読する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ウェルネス レビュー メールを購読すると、ウェルネス ステータス、更新日が近づいているストレージ システム、インストール ベース内のNetApp製品のアップグレードが必要なストレージ システムの概要を記載したメールを毎月受信できます。月次サマリーを確認し、ストレージ システムに対してアクションを実行できるように、ウェルネス レビュー メールが送信されます。サブスクリプションを表示、編集、共有、削除するオプションもあります。メールを受信したくない場合は、いつでもメールの受信を停止できます。

サブスクリプションを有効にしたら、サブスクリプションを追加するときに開始日を選択する必要があります。月ごとの E メールサマリーには、健全性、更新、アップグレード、健全性チェックの未処理のアクションが表示されます。確認用 E メールアドレスを入力すると、指定した E メールアドレスに E メールが送信されます。サブスクリプションを削除することもできます。


NOTE: この機能を使用できるのは、ネットアップの SupportEdge Advisor と SupportEdge Expert のサービスが提供している場合のみです。

.手順
. 左側のペインで、 *Wellness Review* をクリックします。
. [ サブスクリプションの追加 ] をクリックします。
. [ 新規サブスクリプションの追加 ] ダイアログボックスの [ 名前 ] 、 [ カテゴリ * の選択 ] 、 [ 顧客の検索 ] 、および [ 電子メール * ] フィールドに必要な情報を入力します。
. [*Subscribe*] をクリックします
+
サブスクリプションが成功すると、「サブスクリプションが追加されました」というメッセージが表示されます。


