---
sidebar: sidebar 
permalink: task_view_performance_graphs.html 
keywords: performance, performance graph, graphs, digital advisor, performance charts, day, week, 1 month, 2 months, calendar, chart data, performance on node level, graph, node level 
summary: パフォーマンスに関する情報を提供します。 
---
= Digital Advisorでストレージ システムのパフォーマンス グラフを表示する
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
パフォーマンスグラフを使用して、ストレージデバイスのパフォーマンスを分析できます。ONTAP クラスタまたは ONTAP クラスタ / E シリーズコントローラの複数のノードについて、詳細なパフォーマンスグラフを表示できます。これらのグラフには、パフォーマンスの傾向やパターンの分析を理解するために使用できる履歴パフォーマンスデータが表示されます。カレンダーから日付を選択すると、 1 日、 1 週間、 1 カ月、 2 カ月、 12 カ月のパフォーマンスグラフを表示できます。複数のノードを選択すると、特定のグラフを同時に表示できます。

プリファレンスを設定できます。たとえば、 3 つのノードの場合は 1 つのグラフ、 3 つのノードの場合は 2 つのグラフのいずれかを表示できます。

グラフが最初に表示されるとき、1週間分のタブがあらかじめ選択されており、大量のデータとその異なるデータ系列間の関係を理解しやすくするために、1週間分のデータがグラフ形式で表示されます。例えば、日付範囲をリセットしたい場合は、「1か月」タブを選択し、カレンダーで日付を選択できます。

また、パフォーマンスグラフを拡大表示するオプションもあり、個々のデータポイントが表示されます。

video::fWrHYX17xT8[youtube,width=848,height=480]
.手順
. ダッシュボードで「パフォーマンス」を選択します。
+
ONTAP システムでは、*ノード* タブを選択して ONTAP クラスターの単一ノードのパフォーマンスを表示したり、*ローカル ティア* タブを選択してローカル ティアのパフォーマンスを表示したり、*ボリューム* タブを選択してボリュームのパフォーマンスを表示したりすることができます。デフォルトでは、クラスタのパフォーマンスが表示されます。

+
E シリーズシステムの場合、コントローラレベルのグラフしか表示できません。



. 1 日、 1 週間、 1 カ月、 2 カ月、または 12 カ月のいずれかを選択します。 カレンダーで、パフォーマンスデータをグラフ形式で表示します。
+
たとえば、 2 カ月間のデータを表示するには、 2 カ月間のタブを選択します。これにより、パフォーマンス要件に基づいて期間内の特定のデータを表示できます。

. ONTAP のクラスタとノードについて、必要な指標を含む次のパフォーマンスグラフを使用できます。


[cols="25,25,25,25"]
|===
| for Cluster の略 | をクリックします | ローカル階層の場合 | をクリックします 


| IOPS | CPU 利用率 - 最大パフォーマンス（ヘッドルーム） | 平均スループット | IOPS 


| ネットワークスループット | レイテンシ | 平均利用率 | レイテンシ 


|  | IOPS |  |  


|  | プロトコル IOPS |  |  


|  | ネットワークスループット |  |  
|===
. E シリーズコントローラでは、次のパフォーマンスグラフと必須の指標を使用できます。
+
** CPU 利用率
** レイテンシ
** IOPS
** スループット



