---
sidebar: sidebar 
permalink: task_generate_tokens_API_services.html 
keywords: generate token, access token, refresh token, API services 
summary: API にアクセスするためのトークンを生成する方法について説明します。 
---
= API を使用するトークンを生成します
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
API サービスへの登録やトークンの生成は簡単です。

.手順
. [* クイックリンク * （ Quick Links * ） ] メニューから [* API サービス * （ API Services * ） ] をクリックします。
. [*Register] をクリックします。
. 承認フォームに必要事項を入力し、 [*Submit*] をクリックします。
+
アクティブ化は自動的に行われ、瞬時に行われます。Digital Advisor APIの使用が許可されると、プログラムによるAPI呼び出しに使用するトークンを生成できます。これらのトークンを使用して、 API カタログ内から「試してみよう」を実行することもできます。プログラムによって取得されたトークンは、常にアクセストークンとリフレッシュトークンの 2 つのセットで構成されます。アクセストークンは、すべての API を正常に使用するために渡される必要があります（ただし、リフレッシュトークンを使用すると、プログラムによって新しいトークンセットを取得できます）。

. [Main API Services] ページで、 [Generate Token] をクリックしてアクセストークンを表示およびダウンロードし、トークンを更新して API を呼び出します。
+
ポータルでは、 1 つまたは両方のトークンを複数の方法でセットに保存できます。クリップボードにコピーしたり、テキストファイルとしてダウンロードしたり、プレーンテキストで表示したりすることができます。




NOTE: あとで使用できるように、アクセストークンをダウンロードして保存し、トークンを更新する必要があります。アクセストークンは、生成とリフレッシュトークンの1時間後に期限切れになります。トークンは、7日ごとに再生成し、アプリケーションにインストールする必要があります。これを行うには、アプリケーションにログインする必要はありません。ただし、90日が経過したら、アプリケーションにログインして新しいアクセストークンと更新トークンを取得する必要があります。
