---
sidebar: sidebar 
permalink: task_add_config_drift_template.html 
keywords: config deviation, drift, configuration, add template 
summary: 構成ドリフトテンプレートを追加するための情報を提供します。 
---
= 設定ドリフトテンプレートを追加します
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
システム構成とクラスタ構成を比較し、設定の差異をほぼリアルタイムで検出するために、テンプレートを追加する必要があります。設定のドリフトテンプレートは、 AutoSupport データを実行するシステムを使用して追加されます。

* このタスクについて *

設定ドリフトテンプレートの属性は編集可能で、テンプレートの次のグループは、一部のセクションで正規表現をサポートしています。

[cols="3*"]
|===
| グループ | セクション | 属性 


| *集計* | aggr-Info.xmlを選択します | 名前 


| *クラスタ* | cluster-Info.xmlという形式で指定します | クラスタ名 


| * LUN * | LUN.xmlです | 名前 


| * SVM * | vserver-Info.xmlのようになりました | Vserver 


| *ネットワーク* | network-interface.xml | VIF 


| *DNS* | dns.xmlを指定します | ドメイン 


| *音量* | ボリューム.xml | ボリューム 
|===
ユーザは、正規表現を使用して、ボリューム、アグリゲート、クラスタなどの命名の不整合に起因する設定のドリフトレポートを作成できます。たとえば、グループ* aggregate *のセクション* aggr-Info.xml *の属性* Name *に対して正規表現* aggr-name**が指定されている場合、プレフィックス* aggr-name *を含まない属性の値は、設定ドリフトレポートが生成されるときにドリフトとしてマークされます。

.手順
. 左側のペインで、 [Config Drift *] をクリックします。
. [ テンプレートの追加 ] をクリックします。
. 必要な値を指定します。
. オプション：テンプレートをカスタマイズするには、グループを編集するか、テンプレートの不要なグループを削除します。
. [ テンプレートの追加 ] をクリックします。

