---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: renew, hardware, software 
summary: ストレージシステムのソフトウェアとハードウェアを更新するための情報を提供します。 
---
= 容量と Storage Efficiency による削減効果を分析できます
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
システムの容量の詳細および Storage Efficiency による削減効果を表示して、適切な処理を実行できます。容量とストレージ効率の情報は、クラスタレベルまたはノードレベルで表示できます。


NOTE: この機能は E シリーズシステムではサポートされません。

容量のダッシュボードには、システムの容量の詳細と容量予測が表示されます。容量予測では、過去の容量情報を使用して各システムの利用率を特定します。使用容量と割り当て容量の履歴データ（使用可能な場合は 1 年分のデータ）に基づいて、アルゴリズムは各システムの現在の使用率を考慮し、今後 1 ～ 6 か月にわたってシステムの使用率の予測を生成します。

Storage Efficiencyダッシュボードには、ONTAP 9.1以降を実行するストレージシステムについて、データ削減率、使用済み論理スペース、使用済み物理スペース、削減された総データ量が表示されます。データ削減率と削減効果は、AFFシステム、AFF以外のシステム、またはその両方で、Snapshotコピーの有無にかかわらず確認できます。ストレージ全体でのデータ削減量の合計は、ボリューム重複排除、ボリューム圧縮、コンパクション、FlexCloneボリューム、Snapshotコピーなどの効率化機能ごとに確認できます。削減比率が最も高い上位5つのストレージシステムを表示できます。また、ONTAP 9.10以降を実行しているAFF Aシリーズ、AFF C190、オールSANアレイ、FAS500などのONTAPシステムについて、SnapshotコピーなしでSANとNASの効率性をノードレベルで表示することもできます。

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.手順
. 左側のペインで、 * 容量と効率 * をクリックします。
+
デフォルトでは、 * 容量 * タブが選択されています。

. クラスタレベルおよびノードレベルで容量の詳細を表示します。
+
.. ノードレベルの容量予測を表示します。
+
ONTAP システムについては、 Cluster Viewer で物理容量に関する情報を確認できます。

.. 容量の追加 * をクリックして、ネットアップまたはパートナーに容量を追加する通知を送信します。


. ストレージシステムの Storage Efficiency およびデータ削減量を表示します。
+
.. ストレージシステムのストレージ容量削減比率が平均ストレージ容量削減比率を上回る場合は、「 * ユーザ事例を共有」をクリックして、実施したベストプラクティスをお知らせください。
.. ストレージシステムのストレージ容量削減比率が平均ストレージ容量削減比率より低い場合は、「 * お問い合わせ * 」をクリックして、ストレージシステムの構成をお知らせください。




容量およびストレージ効率の詳細については、を参照してください link:reference_aiq_faq.html["Digital Advisorについてのよくある質問です"]。
