---
sidebar: sidebar 
permalink: task_add_watchlist.html 
keywords: dashboard, watchlist, add watchlist 
summary: ダッシュボードに監視リストを追加するための情報を提供します。 
---
= 監視リストを作成します
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
一連のシステムにすばやく簡単にアクセスできる監視リストを作成できます。カテゴリまたはシリアル番号に基づいてシステムを追加できます。


NOTE: 1 つのカテゴリに最大 15,000 台のシステムを追加でき、 1 つのシリアル番号には 500 台のシステムを追加できます。

.手順
. 左側のペインで、「 * Watchlists * 」をクリックします
+
[ 監視リストを管理 ] 画面が表示されます。

. 監視リストを作成 * をクリックします。
. 監視リストの名前を指定します。
. 次のいずれかのオプションを選択してシステムを監視リストに追加します。
+
** *カテゴリ*：お客様、サイト、グループ、Keystoneサブスクリプションなど、特定のカテゴリに関連付けられたインベントリ全体を追加できます。 を監視リストに追加します。
+

NOTE: Keystoneサブスクリプション*オプションを使用すると、Keystoneサブスクリプションに関連付けられているサブスクリプション番号を含めることができます。監視リストで検索すると、Digital Advisorダッシュボードの* Keystone Subscriptions *ウィジェットでサブスクリプションを確認できます。詳細については、を参照してください link:https://docs.netapp.com/us-en/keystone-staas/integrations/keystone-aiq.html#search-by-keystone-watchlists["Keystone監視リストで検索"^]。

** *シリアル番号*：このオプションを使用すると、指定したシリアル番号に基づいて監視リストにインベントリを含めることができます。シリアル番号を直接入力するか、お客様、サイト、グループなどのカテゴリからシリアル番号を選択できます。


. 監視リストを作成 * をクリックします。
+
監視リストダッシュボードが表示されます。


