---
sidebar: sidebar 
permalink: task_view_inventory_details.html 
keywords: inventory, platforms, systems, clusters, sites 
summary: 所有しているインベントリ全体に関する情報が表示されます。 
---
= Digital Advisorでストレージ システムのインベントリの詳細を表示します
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
*インベントリ* ウィジェットには、所有するシステムの合計数とサポート対象のスイッチのロールアップが表示されます。これには、Digital Advisor対応製品と非対応製品の両方が含まれます。

選択した監視リストのレポートを生成し、レポートを最大 5 名の受信者に E メールで送信することもできます。

video::ttbpbT5uTBI[youtube,width=848,height=480]


[[view-system-details]]
== システムの詳細を表示します

.手順
. *Inventory* ウィジェットで、*Systems* を選択するとすべてのプラットフォームのシステム情報が表示されます。または、プラットフォームの種類を選択してから *Systems* を選択すると、そのプラットフォーム固有のシステムが表示されます。
. システムの詳細情報を表示するには、ノードまたはクラスタを選択してください。
. 「ダウンロード」を選択すると、システムの詳細を .xls 形式で表示する「インベントリ」レポートをダウンロードできます。
. *ダウンロード*を選択すると、*Ansible Inventory*レポートがダウンロードされ、リージョンまたはサイトレベルでのシステム詳細が.ymlおよび.ini形式で表示されます。
+
Ansible のインベントリファイルは、カスタマイズされた Ansible Playbook ファイルと併用し、インフラ構成を変更することができます。





[[view-support-entitled-switch-details]]
== サポート対象のスイッチの詳細を表示

.手順
. 「Inventory」ウィジェットで「Support Entitled Switches」を選択すると、サポート対象のすべてのスイッチに関する情報が表示されます。

