---
sidebar: sidebar 
permalink: task_view_inventory_details.html 
keywords: inventory, platforms, systems, clusters, sites 
summary: 所有しているインベントリ全体に関する情報が表示されます。 
---
= インベントリの詳細を表示します
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
*インベントリ* ウィジェットには、所有するシステムの合計数とサポート対象のスイッチのロールアップが表示されます。これには、Digital Advisor対応製品と非対応製品の両方が含まれます。

選択した監視リストのレポートを生成し、レポートを最大 5 名の受信者に E メールで送信することもできます。

video::ttbpbT5uTBI[youtube,width=848,height=480]


== システムの詳細を表示します

.手順
. [* インベントリ（ * Inventory ） ] ウィジェットで、 [* システム * （ * Systems * ） ] をクリックしてすべてのプラットフォームのシステム情報を表示するか、プラットフォームタイプをクリックし、 [ * システム * （ * Systems * ） ] をクリックして、そのプラットフォームに固有のシステムを表示します。
. ノードまたはクラスタをクリックすると、システムに関する詳細情報が表示されます。
. システムの詳細を .xls 形式で表示するには、 * Inventory * レポートをダウンロードします。
. Ansible Inventory * レポートをダウンロードして、地域またはサイトレベルの .yml および .ini 形式でシステムの詳細を確認できます。
+
Ansible のインベントリファイルは、カスタマイズされた Ansible Playbook ファイルと併用し、インフラ構成を変更することができます。





== サポート対象のスイッチの詳細を表示

.手順
. *インベントリ* ウィジェットで、*サポート対象スイッチ* をクリックすると、サポート対象スイッチすべてに関する情報が表示されます。

