---
sidebar: sidebar 
permalink: task_analyze_storage_efficiency.html 
keywords: capacity, storage efficiency, data reduction, savings 
summary: ストレージシステムの容量詳細とストレージ効率による節約効果をご確認ください。 
---
= Digital Advisorで容量とストレージ効率の節約を表示
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
システムの容量の詳細および Storage Efficiency による削減効果を表示して、適切な処理を実行できます。容量とストレージ効率の情報は、クラスタレベルまたはノードレベルで表示できます。


NOTE: この機能は E シリーズシステムではサポートされません。

容量ダッシュボードには、システムの容量の詳細と容量予測が表示されます。容量予測では、過去の容量情報を使用して各システムの利用状況を把握します。使用済み容量と割り当て済み容量の履歴データ（利用可能な場合は1年分のデータ）に基づいて、アルゴリズムは各システムの現在の使用状況を考慮し、今後1～6か月間のシステムの利用状況の予測を生成します。

ストレージ効率ダッシュボードには、データ削減比率、使用されている論理領域、使用されている物理領域、および保存されたデータの総量が表示されます。データ削減比率と節約量は、AFFシステム、非AFFシステム、またはその両方について、スナップショットコピーの有無で確認できます。顧客ストレージ全体でのデータ削減量は、ボリューム重複排除、ボリューム圧縮、コンパクション、FlexCloneボリューム、およびスナップショットコピーなどの効率化機能ごとに確認できます。効率比率が最も高いストレージシステムの上位5機種を表示できます。AFF A-Series、AFF C190、All SAN Array、FAS500などのONTAPシステムについて、ノードレベルでスナップショットコピーなしのSANおよびNASの効率を確認することもできます。

video::8Ge3_0qlyxA[youtube,width=848,height=480]
.手順
. 左側のペインで、 * 容量と効率 * をクリックします。
+
デフォルトでは、 * 容量 * タブが選択されています。

. クラスタレベルおよびノードレベルで容量の詳細を表示します。
+
.. ノードレベルの容量予測を表示します。
+
ONTAP システムについては、 Cluster Viewer で物理容量に関する情報を確認できます。

.. 容量の追加 * をクリックして、ネットアップまたはパートナーに容量を追加する通知を送信します。


. ストレージシステムの Storage Efficiency およびデータ削減量を表示します。
+
.. ストレージシステムのストレージ容量削減比率が平均ストレージ容量削減比率を上回る場合は、「 * ユーザ事例を共有」をクリックして、実施したベストプラクティスをお知らせください。
.. ストレージシステムのストレージ容量削減比率が平均ストレージ容量削減比率より低い場合は、「 * お問い合わせ * 」をクリックして、ストレージシステムの構成をお知らせください。




容量およびストレージ効率の詳細については、を参照してください link:reference_aiq_faq.html["Digital Advisorについてのよくある質問です"]。
