---
sidebar: sidebar 
permalink: task-informed-decisions-based-on-cloud-recommendations.html 
keywords: cloud recommendations, migration, backup and archive, disaster recovery, FabricPool, FabricPool Advisor, inactive data, tiered data, IDR 
summary: 十分な情報に基づいて決定を下すことができる推奨事項を提供します。 
---
= クラウドに関する推奨事項に基づいて、十分な情報に基づいて意思
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Digital Advisorはシステムを絶えず分析し、推奨事項を提供してシステムのパフォーマンス、効率、および健全性を改善します。


NOTE: Digital Advisor は、推奨事項を実装するためにNetAppコンソールに移動します。



== データ移行

ストレージシステム内で使用可能なさまざまなタイプのワークロードに関する情報を提供し、クラウドに対応しているワークロードを特定します。ワークロードをクラウドに移行することで、コストを削減し、クラウドを使用したディザスタリカバリを実現できます。

Cloud Volumes ONTAP （CVO）とCloud Volumes Service （CVS）への移行については、次の基準を満たすボリュームが推奨されます。

* ボリュームは、NFS、SMB、CIFS、FCP、またはiSCSIのいずれかのプロトコルを使用している必要があります
* ルートボリュームは除外されます
* ボリューム内のワークロードは、Oracle、SAP、SAP HANA、MSSQL、MySQL、 SharePoint、FileShare、仮想化、Trident
* システムの使用年数が1年を超えています
* サポート契約は6カ月以内に終了します


.手順
. 左側のペインで、*クラウドの推奨事項*をクリックします。
. [* Migration *（移行*）]ペインで任意のリンクをクリックします。
. *クラウドに移行* をクリックして *コンソール* を起動します。




== 階層化

アクセス頻度の低いローカル階層（アグリゲート）データ、アクセス頻度の低いボリュームデータ、階層化されたデータ、監視対象外のデータに関する情報が表示されます。コールドデータや非アクティブデータを監視して低コストのオブジェクトストレージ階層に階層化することで、ストレージの設置面積と関連コストを削減できます。


NOTE: Inactive Data Reporting （ IDR ）を有効にして、 Ansible Playbook ファイルを含む zip ファイルを生成することができます。この情報は、顧客、サイト、グループ、監視リスト、クラスタ、ノードの各レベルで確認できます。

階層化では、次の条件を満たすボリュームが推奨されます。

* ボリュームでNFS、SMB、またはCIFSプロトコルが使用されている必要があります
* ルートボリュームは除外されます
* アクセス頻度の低いデータが50%を超えています
* アグリゲート容量が50%を超えています


.手順
. 左側のペインで、*クラウドの推奨事項*をクリックします。
. 「*階層化*」パネルのいずれかのリンクをクリックします。
. *Tier Data* をクリックして *Console* を起動します。


FabricPool の詳細については、を参照してください link:https://www.netapp.com/pdf.html?item=/media/17239-tr4598pdf.pdf["FabricPool のベストプラクティス"^]。



== バックアップとアーカイブ

クラウドにバックアップするシステムに関する情報が表示されます。NetApp Cloud Backupを使用して、システムを保護し、必要に応じてリストアすることができます。

クラウドへのバックアップには、次の基準を満たすボリュームが推奨されます。

* ルートボリュームは除外されます
* ソースボリュームとデスティネーションシステム、およびSnapVault バックアップを含むボリュームは除外されます。


.手順
. 左側のペインで、*クラウドの推奨事項*をクリックします。
. [* Backup & Archive]ペインで任意のリンクをクリックします。
. *クラウドへのバックアップ* をクリックして *コンソール* を起動します。




== レプリケーション

災害発生時にクラウドにレプリケートする必要があるデータに関する情報を提供します。

クラウドへのレプリケーションには、次の基準を満たすボリュームが推奨されます。

* ルートボリュームは除外されます
* SnapMirrorソースボリュームは除外されます
* SnapMirrorデスティネーションボリューム（ボリュームタイプLSおよびDP）は除外されます


.手順
. 左側のペインで、*クラウドの推奨事項*をクリックします。
. [* Disaster Recovery]ペインで任意のリンクをクリックします。
. *クラウドに複製* をクリックして *コンソール* を起動します。

