---
sidebar: sidebar 
permalink: upgrade_advisor_overview.html 
keywords: Upgrade Advisor, upgrade plan, ONTAP, upgrade recommendation, clusters, storage systems 
summary: ONTAPアップグレードの計画を簡易化するUpgrade Advisorの概要を示します。 
---
= 概要
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Upgrade Advisorでは、ONTAPのアップグレードまたはリバートを成功させるために必要な詳細およびステップバイステップの情報を含むアップグレード計画を生成できます。

単一のクラスタおよび複数のクラスタに対して、自動無停止アップグレードプランを生成できます。単一のクラスタのアップグレードの推奨事項を表示できます。これには、クラスタに関連するリスクのリスト、アップグレードのブロックと警告のリストを含むアップグレード前チェックレポート、新機能と拡張機能に関する情報が含まれます。複数のクラスタに対してはアップグレードの推奨事項は提供されません。詳細については、を参照してください link:generate_upgrade_plan_single_multiple_clusters.html["単一クラスタおよび複数クラスタのアップグレードプランの生成"]。

[NOTE]
====
* MetroCluster構成のクラスタごとに、個別のアップグレードプランを生成して、アップグレード手順全体を確認します。
* クラスタでONTAP 9.6以前のバージョンが実行されている場合は、アップグレードの推奨事項の新機能と機能拡張に関する情報を確認できます。アップグレード前チェックレポートとリスク概要は使用できません。古い形式のアップグレードプランを生成できます。


====
アップグレードプランを生成する前に、ONTAPアップグレードの準備をしておく必要があります。適切な準備を行うことで、アップグレードプロセスを開始する前に、アップグレードの潜在的なリスクや障害を特定して軽減することができます。詳細については、を参照してください link:https://docs.netapp.com/us-en/ontap/upgrade/prepare.html["ONTAPのアップグレードを準備する"^]。
